import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import AppFrame,{WorkspaceContent} from '../components/AppFrame';
import AgenciesPanel from '../components/AgenciesPanel';
import AgencyHierarchy,{AgencyLogo,AgencyFilter} from '../components/AgencyHierarchy';
import {useOrganization,agencyFor,inAgency} from '../organization';
import {examplePublishers} from './examples';
import '../dashboard-styles';
function AgencyWorkspace(){
  const controller=useOrganization('/test-api/organization'),[section,setSection]=useState('Agencies'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(examplePublishers[0].sites[0].id),[publisherId,setPublisher]=useState(examplePublishers[0].id),[closed,setClosed]=useState<Record<string,boolean>>({});
  const publisher=examplePublishers.find(p=>p.id===publisherId),site=publisher?.sites.find(s=>s.id===selected),agency=agencyFor(controller.data,publisher?.id);
  useEffect(()=>{if(publisherId&&!inAgency(controller.data,publisherId,filter))setFilter('all');},[controller.data]);
  function select(id:string,siteId?:string){const p=examplePublishers.find(p=>p.id===id);if(!p)return;setPublisher(id);setSelected(siteId??(id===publisherId?selected:p.sites[0]?.id??''));setSection('Publishers');}
  function filterAgency(id:string){setFilter(id);if(!publisher||!inAgency(controller.data,publisher.id,id)){const next=examplePublishers.find(p=>inAgency(controller.data,p.id,id));setPublisher(next?.id??'');setSelected(next?.sites[0]?.id??'');}}
  return <AppFrame logoSrc="/layout-preview-logo.png" account={<div className="auth-account-card"><strong>TEST workspace</strong><a href="/">Home ↗</a></div>} navigation={<nav className="main-nav" aria-label="Main navigation">{['Publishers','Agencies'].map(s=><button key={s} type="button" className={'nav-item'+(section===s?' active':'')} onClick={()=>setSection(s)}>{s}</button>)}<a className="nav-item" href="/api-integrations">API integracije</a><a className="nav-item" href="/creative-templates">Creative templates</a><a className="nav-item" href="/prebid-settings">Prebid builds</a><a className="nav-item" href="/site-workspace">Site workspace</a></nav>}
    sidebarContent={<div className="publisher-nav publisher-tree"><div className="section-label">Agencies / Publishers</div><AgencyHierarchy data={controller.data} publishers={examplePublishers} filter={filter} onFilter={filterAgency} onManage={()=>setSection('Agencies')} renderPublisher={(p,searching)=><div key={p.id} className="publisher-tree-group"><div className="publisher-account-row"><button type="button" className="publisher-collapse" aria-label={`Toggle sites for ${p.name}`} aria-expanded={searching||!closed[p.id]} onClick={()=>setClosed({...closed,[p.id]:!closed[p.id]})}>{searching||!closed[p.id]?'▾':'▸'}</button><button type="button" className={'publisher-account-link'+(p.id===publisherId?' active':'')} onClick={()=>select(p.id)}><span>{p.name}</span><small>{p.sitesCount}</small></button></div>{searching||!closed[p.id]?<div className="publisher-site-list">{p.sites.map(s=><button key={s.id} type="button" className={'site-link'+(s.id===selected?' active':'')} onClick={()=>select(p.id,s.id)}>{s.name}</button>)}</div>:null}</div>}/></div>}>
    <main className="workspace"><header className="topbar"><div><span className="eyebrow agency-selection-breadcrumb">{section==='Agencies'?'TEST / Organization':`${agency?.name??'Without agency'} / ${publisher?.name??'No publisher'} / ${site?.name??'No site'}`}</span><h1>{section==='Agencies'?'Agencies':site?.name??publisher?.name??'No publisher selected'}</h1><p>TEST uses example publishers and sites. Agency names, logos and assignments are saved.</p></div></header><WorkspaceContent pageKey={section+selected}>{section==='Agencies'?<AgenciesPanel controller={controller} publishers={examplePublishers} onOpenPublisher={id=>{setFilter('all');select(id);}} onOpenAgency={id=>{filterAgency(id);setSection('Publishers');}}/>:<section className="content-page"><article className="panel"><h2>Agency → Publisher → Site</h2><div className="agency-overview"><div className="agency-overview-identity"><AgencyLogo agency={agency}/><strong>{agency?.name??'Without agency'}</strong></div><AgencyFilter data={controller.data} value={filter} onChange={filterAgency}/></div><h3>{publisher?.name??'No publisher in this agency'}</h3><p>{site?.domain}</p><p>Use Agencies to assign or move this publisher and all its sites.</p><button type="button" className="button secondary" onClick={()=>setSection('Agencies')}>Manage agencies</button></article></section>}</WorkspaceContent></main>
  </AppFrame>;
}
createRoot(document.getElementById('root')!).render(<AgencyWorkspace/>);
