from pathlib import Path


def replace_once(path: str, old: str, new: str, label: str) -> None:
    file_path = Path(path)
    source = file_path.read_text(encoding='utf-8')
    if new in source:
        return
    if old not in source:
        raise SystemExit(f'{label} anchor was not found in {path}.')
    file_path.write_text(source.replace(old, new, 1), encoding='utf-8')


replace_once(
    'src/App.tsx',
    '''        <div className="brand">
          <div className="brand-mark">PP</div>
          <div><strong>Prebid Professor</strong><span>Ad-tech control plane</span></div>
        </div>''',
    '''        <div className="brand">
          <div className="brand-mark" aria-hidden="true">
            <img alt="" src="/tessera-logo.svg" />
          </div>
          <div><strong>Tessera</strong><span>Ad-tech control plane</span></div>
        </div>''',
    'sidebar brand',
)
replace_once(
    'src/App.tsx',
    "<h1>{site?.name ?? publisher?.name ?? 'Prebid Professor'}</h1>",
    "<h1>{site?.name ?? publisher?.name ?? 'Tessera'}</h1>",
    'workspace fallback title',
)

replace_once(
    'src/styles.css',
    '''.brand-mark {
  width: 42px;
  height: 42px;
  display: grid;
  place-items: center;
  border-radius: 10px;
  color: #1c1510;
  background: #f2762e;
  font-weight: 900;
}''',
    '''.brand-mark {
  width: 44px;
  height: 44px;
  flex: 0 0 44px;
  border-radius: 11px;
  overflow: hidden;
  box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.06);
}

.brand-mark img {
  width: 100%;
  height: 100%;
  display: block;
}''',
    'sidebar logo styles',
)

replace_once(
    'worker/auth.ts',
    '<title>Sign in · Prebid Professor</title>',
    '<title>Sign in · Tessera</title>',
    'login page title',
)
replace_once(
    'worker/auth.ts',
    '''    .mark { width: 46px; height: 46px; display: grid; place-items: center; border-radius: 12px; color: #1c1510; background: #f2762e; font-weight: 900; }
    .brand strong, .brand span { display: block; }''',
    '''    .mark { width: 46px; height: 46px; border-radius: 12px; overflow: hidden; box-shadow: 0 0 0 1px rgba(255, 255, 255, .07); }
    .mark svg { width: 100%; height: 100%; display: block; }
    .brand strong, .brand span { display: block; }''',
    'login logo styles',
)
replace_once(
    'worker/auth.ts',
    '    <div class="brand"><div class="mark">PP</div><div><strong>Prebid Professor</strong><span>Ad-tech control plane</span></div></div>',
    '''    <div class="brand"><div class="mark" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><rect width="600" height="600" rx="130" fill="#171b22"/><rect x="87" y="100" width="126" height="125" rx="25" fill="#e5e7eb"/><rect x="387" y="100" width="126" height="125" rx="25" fill="#9aa1b0"/><rect x="237" y="250" width="126" height="125" rx="25" fill="#7d8494"/><rect x="237" y="400" width="126" height="100" rx="25" fill="#565e70"/><rect x="238" y="86" width="126" height="126" rx="25" fill="#e58936" transform="rotate(12 301 149)"/></svg></div><div><strong>Tessera</strong><span>Ad-tech control plane</span></div></div>''',
    'login brand',
)

replace_once(
    'worker/releases.ts',
    "const output = ['/* Generated by Prebid Professor. */'];",
    "const output = ['/* Generated by Tessera. */'];",
    'minimum-height CSS header',
)
replace_once(
    'worker/releases.ts',
    "    ' * Prebid Professor sticky ad styles',",
    "    ' * Tessera sticky ad styles',",
    'sticky CSS header',
)
replace_once(
    'worker/releases.ts',
    'return `<!-- Prebid Professor implementation for ${snapshot.site.name} -->',
    'return `<!-- Tessera implementation for ${snapshot.site.name} -->',
    'implementation header',
)
replace_once(
    'worker/runtime-controls-release.ts',
    ' * Prebid Professor generated runtime',
    ' * Tessera generated runtime',
    'generated runtime header',
)
replace_once(
    'worker/ads-txt.ts',
    "'user-agent': 'Prebid-Professor-AdsTxt-Checker/1.0',",
    "'user-agent': 'Tessera-AdsTxt-Checker/1.0',",
    'ads.txt checker user agent',
)
replace_once(
    'worker/app-deploy.ts',
    "const RUNTIME_BUILD = '2026-07-19-release-diff-v17';",
    "const RUNTIME_BUILD = '2026-07-19-tessera-branding-v18';",
    'runtime build marker',
)

replace_once(
    'README.md',
    '# Prebid Professor\n\nCloudflare-hosted dashboard and release manager for Prebid.js publisher integrations.',
    '# Tessera\n\nCloudflare-hosted AdOps control plane and release manager for publisher integrations. The technical repository and Worker identifiers remain `prebid-professor` for deployment compatibility.',
    'README branding',
)

print('Tessera branding applied.')
