const escape = (s) => String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style = `:root{font-family:Inter,system-ui,-apple-system,sans-serif;color:#202a3b;background:#edf0f5}*{box-sizing:border-box}body{margin:0}header{background:#171c24;color:white;padding:20px 28px;display:flex;justify-content:space-between;align-items:center;gap:16px}header strong{font-size:22px}.badge{font-size:11px;font-weight:800;background:#fff0df;color:#a4430c;padding:6px 10px;border-radius:20px}main{max-width:1040px;margin:32px auto;padding:0 20px}.card{background:#fff;border:1px solid #d7dfec;border-radius:16px;padding:24px;margin-bottom:20px}h1{font-size:26px;margin:0 0 12px}h2{font-size:20px;margin:0 0 12px}p{line-height:1.6;color:#5c6b80}label{display:block;margin:14px 0 6px;font-weight:650}input:not([type=checkbox]){width:100%;padding:12px;border:1px solid #c9d2df;border-radius:9px;font:inherit}button,.button{display:inline-block;border:1px solid #ccd5e2;border-radius:9px;padding:11px 16px;cursor:pointer;font:inherit;font-weight:750;text-decoration:none;background:white;color:#37455b}button.primary{background:#f47725;border-color:#e76b1b;color:#231a12}button:disabled{opacity:.5;cursor:default}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.message{border-radius:10px;padding:14px;background:#e9f5ed;white-space:pre-wrap;margin:16px 0}.error{background:#fff1ef;color:#9b2723}pre{max-height:320px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f7fa;padding:16px;font-size:12px;border-radius:9px}small{color:#66758c}ul{padding-left:20px;line-height:1.9}li{overflow-wrap:anywhere}article{border:1px solid #d9e1ed;border-radius:10px;padding:16px;margin:12px 0}article strong{display:block}.hash{overflow-wrap:anywhere;font-family:monospace;font-size:12px}.hidden,[hidden]{display:none!important}summary{cursor:pointer;font-weight:700;padding:10px 0}.login{max-width:470px}input:focus,button:focus-visible,a:focus-visible{outline:3px solid #ffc195;outline-offset:2px}@media(max-width:600px){header{padding:16px}.card{padding:18px}main{margin:20px auto;padding:0 12px}h1{font-size:22px}.badge{max-width:150px;text-align:center}}`;
const wrap = (body, script=false) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tessera · Test workspace</title><style>${style}</style></head><body><header><strong>Tessera</strong><span class="badge">TEST · NO LIVE PUBLISHING</span></header>${body}${script?'<script src="/workspace.js" defer></script>':''}</body></html>`;
export function loginPage(error='') {
  return wrap(`<main class="login"><section class="card"><h1>Sign in to test</h1><p>Use your separate test credentials. This workspace does not change the live platform.</p>${error?`<div class="message error" role="alert">${escape(error)}</div>`:''}<form action="/api/auth/login" method="post"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="username" required><label for="password">Test password</label><input id="password" name="password" type="password" autocomplete="current-password" required><div class="actions"><button class="primary" type="submit">Sign in</button></div></form></section></main>`);
}
export function workspacePage(email) {
  return wrap(`<main><section class="card"><h1>Generate and save a test release</h1><p>One isolated test copy, initially <strong>example.invalid</strong>. Generate with the built-in runtime, save the exact package and reopen it. No ads run on this screen. Saved packages can be delivered to a separate TEST address from the deployment page.</p><small>Signed in as ${escape(email)}</small><div class="actions"><a class="button" href="/site-workspace#packages">Generate and releases</a><a class="button" href="/site-settings">Site and ad positions</a><a class="button" href="/prebid-settings">Prebid and bidders</a><a class="button" href="/runtime-selection">Script version</a><a class="button" href="/pilot/tanjug">Tanjug TEST paket</a><a class="button" href="/deployments">TEST objave i verzije</a><a class="button" href="/experiments">A/B TEST</a><button id="logout">Sign out</button></div><div id="message" class="message" role="status">Checking test workspace…</div></section><section id="setup" class="card" hidden><h2>Prepare test data</h2><p>The test database is empty. This creates one demo site and the tables needed for test releases. Existing or unrecognized databases are refused. No production records are copied.</p><button id="initialize" class="primary">Prepare empty test database</button></section><section id="generator" class="card" hidden><h2>1. Generate</h2><p id="runtime"></p><p id="takeover-summary">Loading saved TakeOver setting…</p><a class="button" href="/site-settings#positions">Ad positions and TakeOver</a><div class="actions"><button id="generate" class="primary">Generate test package</button></div></section><section id="review" class="card" hidden><h2>2. Review and save</h2><p id="review-summary"></p><div id="package-hash" class="hash"></div><ul id="files"></ul><details><summary>Show generated ads.js as text</summary><pre id="source"></pre></details><label for="note">Version note (optional)</label><input id="note" maxlength="160" placeholder="Example: checking TakeOver"><label><input id="ack" type="checkbox"> I reviewed this test package. This does not publish it.</label><div class="actions"><button id="save" class="primary" disabled>Save test release</button></div><small>Review is valid for 20 minutes. Retrying Save keeps the same package.</small></section><section id="history" class="card" hidden><h2>3. Saved test releases</h2><p>Reopening verifies the original saved files; it does not regenerate them. Up to 20 test packages are retained, including interrupted uploads.</p><button id="refresh">Refresh list</button><div id="releases"></div><div id="opened" hidden><h3>Verified saved package</h3><pre id="opened-details"></pre></div></section></main>`,true);
}
export const workspaceScript = `
'use strict';
const el=(id)=>document.getElementById(id); let reviewed=null, busy=false, runtimeInvalid=false;
function message(text,error=false){el('message').textContent=text;el('message').classList.toggle('error',error);}
async function api(path,body){const response=await fetch('/test-api/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(response.status===401){location.assign('/login');throw Error('Please sign in again.');}if(!response.ok)throw Error(data.error||'Request failed.');return data;}
function lock(value){busy=value;for(const button of document.querySelectorAll('button'))button.disabled=value;el('generate').disabled=value||runtimeInvalid;el('save').disabled=value||!reviewed||!el('ack').checked;}
async function action(fn){if(busy)return;lock(true);try{await fn();}catch(e){message(e.message,true);}finally{lock(false);}}
function showTakeOver(value){el('takeover-summary').textContent=value?.enabled?'TakeOver: ON · saved site settings':'TakeOver: OFF · saved site settings';}
function resetReview(){reviewed=null;el('ack').checked=false;el('review').hidden=true;el('save').disabled=true;}
async function history(){const data=await api('releases');el('releases').replaceChildren();for(const row of data.releases){const item=document.createElement('article');const title=document.createElement('strong');title.textContent=row.note||'Test release';const desc=document.createElement('p');desc.textContent=row.runtimeVersion+' · '+row.fileCount+' files · '+row.storageState+' · '+row.createdAt;const hash=document.createElement('div');hash.className='hash';hash.textContent=row.packageSha256;item.append(title,desc,hash);if(row.storageState==='stored'){const actions=document.createElement('div');actions.className='actions';const open=document.createElement('button');open.textContent='Open saved release';open.addEventListener('click',()=>action(async()=>{const result=await api('releases/'+row.id);el('opened-details').textContent=JSON.stringify(result,null,2);el('opened').hidden=false;message('Saved files verified. This is the original package, not a new generation.');}));const download=document.createElement('a');download.className='button';download.textContent='Download saved ZIP';download.href='/test-api/releases/'+encodeURIComponent(row.id)+'/download';actions.append(open,download);item.append(actions);}el('releases').append(item);}if(!data.releases.length)el('releases').textContent='No saved test releases yet.';}
async function status(){const data=await api('status');runtimeInvalid=Boolean(data.validationIssue);el('setup').hidden=data.ready;el('generator').hidden=!data.ready;el('history').hidden=!data.ready;el('runtime').textContent=data.runtime?'Built-in runtime '+data.runtime.version+' · saved TEST configuration':'Choose an available Script version to generate a new package.';if(data.ready){showTakeOver(data.takeOver);await history();message(data.validationIssue||'Test workspace ready. Start with Generate.',runtimeInvalid);}else message('Prepare the empty test database once to begin.');}
el('initialize').addEventListener('click',()=>action(async()=>{await api('setup',{confirm:'prepare-empty-test-database'});await status();}));
el('generate').addEventListener('click',()=>action(async()=>{resetReview();const data=await api('generate',{acknowledge:true});reviewed=data;showTakeOver(data.takeOver);el('review-summary').textContent=data.descriptor.runtime.runtimeVersion+' · '+data.descriptor.files.length+' files · '+Math.round(data.descriptor.byteSize/1024)+' KB · TakeOver '+(data.takeOver.enabled?'ON':'OFF');el('package-hash').textContent=data.descriptor.packageSha256;el('files').replaceChildren();for(const file of data.descriptor.files){const li=document.createElement('li');li.textContent=file.name+' — '+file.byteSize+' bytes';el('files').append(li);}el('source').textContent=data.adsJs;el('review').hidden=false;message('Package generated. Review it, then save the exact version.');}));
el('ack').addEventListener('change',()=>{el('save').disabled=busy||!reviewed||!el('ack').checked;});
el('save').addEventListener('click',()=>action(async()=>{if(!reviewed||!el('ack').checked)return;const result=await api('save',{receipt:reviewed.receipt,acknowledge:true,note:el('note').value});message(result.created?'Test release saved. Reopen it below.':'This exact test package was already saved; no duplicate was created.');await history();}));
el('refresh').addEventListener('click',()=>action(history));el('logout').addEventListener('click',()=>action(async()=>{const response=await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});if(!response.ok)throw Error('Sign out failed.');location.assign('/login');}));
action(status);
`;
