import { fetchPrebidVersions } from './prebid-versions.mjs';
export function prebidPage(){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tessera · Prebid and bidders</title><style>
:root{font-family:Inter,system-ui,-apple-system,sans-serif;color:#202a3b;background:#edf0f5}*{box-sizing:border-box}body{margin:0}header{background:#171c24;color:white;padding:20px 28px;display:flex;justify-content:space-between;gap:16px;align-items:center}header strong{font-size:22px}.badge{font-size:11px;font-weight:800;background:#fff0df;color:#a4430c;padding:6px 10px;border-radius:20px}main{max-width:1120px;margin:28px auto;padding:0 20px}.card{background:white;border:1px solid #d7dfec;border-radius:16px;padding:24px;margin:0 0 20px}h1{font-size:27px;margin:0 0 12px}h2{font-size:21px;margin-top:0}p{line-height:1.55;color:#5c6b80}.muted{font-size:13px;color:#66758c}label{display:block;font-weight:650;margin:12px 0 6px}input,select,textarea{max-width:100%;font:inherit;border:1px solid #c9d2df;border-radius:8px;padding:10px;background:white;color:inherit}select,textarea,input[type=file]{width:100%}textarea{font-family:ui-monospace,monospace;font-size:13px;resize:vertical;min-height:96px}button,a.button{display:inline-block;border:1px solid #ccd5e2;border-radius:9px;padding:11px 16px;cursor:pointer;font:inherit;font-weight:750;text-decoration:none;background:white;color:#37455b}button.primary{background:#f47725;border-color:#e76b1b;color:#231a12}button.remove{color:#a42e2c;padding:8px 12px}button:disabled{opacity:.5;cursor:default}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.message{border-radius:10px;padding:14px;background:#e9f5ed;white-space:pre-wrap;margin:16px 0;overflow-wrap:anywhere}.error{background:#fff1ef;color:#9b2723}.hash{overflow-wrap:anywhere;font-family:monospace;font-size:12px}fieldset{padding:0;margin:0;border:0;min-width:0}.row{display:grid;grid-template-columns:minmax(160px,1fr) minmax(220px,2fr) 100px;gap:14px;border:1px solid #dce3ed;border-radius:11px;padding:16px;margin:14px 0}.row>div{min-width:0}.override{grid-template-columns:1fr 1fr 1fr;}.override .params{grid-column:1 / -1}.toggle{display:flex;align-items:center;gap:8px}details{margin:18px 0}summary{font-weight:750;cursor:pointer}input:focus,select:focus,textarea:focus,button:focus-visible,a:focus-visible{outline:3px solid #ffc195;outline-offset:2px}@media(max-width:660px){header{padding:16px}.badge{max-width:150px;text-align:center}main{padding:0 12px;margin:20px auto}.card{padding:18px}.row,.override{grid-template-columns:1fr}.override .params{grid-column:auto}}
</style></head><body><header><strong>Tessera</strong><span class="badge">TEST · NO LIVE PUBLISHING</span></header><main>
<section class="card"><h1>Prebid and bidders</h1><p id="site">Loading saved settings…</p><p>Set bidders and options → download the configuration → build on Prebid → return prebid.js → save the final package.</p><div class="actions"><a class="button" href="/site-settings">Site and ad positions</a><a class="button" href="/runtime-selection">Script version</a><a class="button" href="/">Back to Generate</a></div><div id="message" class="message" role="status">Loading…</div></section>
<fieldset id="editor" disabled><section class="card"><h2>1. Bidders and options</h2><p>Add each partner once. Enter its parameters as a JSON object, for example the object provided by that partner. These are placement settings, not an account password.</p><div id="bidders"></div><button id="add-bidder">Add bidder</button><details id="override-section"><summary>Overrides by device, ATF/BTF or ad position</summary><p class="muted">Parameters are combined in this order: base → device → ATF/BTF → exact ad position. Later values replace matching earlier keys. Empty effective parameters skip that bidder for the position.</p><div id="overrides"></div><button id="add-override">Add override</button></details></section>
<section class="card"><details id="build-options"><summary>Build options and User IDs</summary><p>CMP consent and TCF enforcement are included automatically.</p><label class="toggle"><input id="floors-enabled" type="checkbox"> Price floors</label><label for="hard-floor">Hard floor</label><input id="hard-floor" type="number" min="0" max="1000" step="0.01"><label for="currency">Ad server currency</label><input id="currency" maxlength="3"><label class="toggle"><input id="currency-conversion" type="checkbox"> Currency conversion</label><details><summary>User IDs</summary><p class="muted">Enable only the services you use and enter their partner settings. Disabled settings are retained.</p><div id="user-ids"></div></details></details></section>
<section class="card"><h2>2. Get the Prebid configuration</h2><p>Save and download below. Then open Prebid and use <strong>Upload Configuration</strong> to load the JSON.</p><label for="plan-version">Prebid version for this build</label><input id="plan-version" placeholder="11.11.0"><details id="version-options"><summary>Choose another version</summary><label for="available-versions">Versions offered by Prebid</label><select id="available-versions"><option value="">Loading available versions…</option></select><div class="actions"><button id="load-versions">Retry version list</button></div></details><p id="version-note" class="muted" role="status"></p><div class="actions"><button id="download-config" class="primary">Save &amp; download prebid-config.json</button><button id="open-builder">Open Prebid builder</button></div><p class="muted">This saves your preparation on TEST so you can return later. Your active Prebid selection changes only when you save the returned file below.</p><details id="module-details"><summary>Automatic module details</summary><p id="plan-state" role="status">Choose your bidders and options.</p><div id="plan-modules" class="hash"></div></details><details id="save-later"><summary>Save preparation without downloading</summary><button id="save-plan">Save build preparation</button></details></section>
<section class="card"><h2>3. Return prebid.js and save</h2><p>The original file is stored unchanged. Uploading alone does not replace the selected version or change existing packages.</p><label for="upload-file">Prebid.js file · maximum 8 MiB</label><input type="file" id="upload-file" accept=".js,application/javascript,text/javascript"><div class="actions"><button id="upload">Upload file</button></div><p class="muted">Use the original build with its Prebid.js version and Modules header. File checks do not certify partner approval or live ad delivery.</p><h3>Choose the returned file</h3><label class="toggle"><input id="enable-prebid" type="checkbox"> Enable Prebid for newly generated packages</label><label for="build">Saved file</label><select id="build"></select><p id="file-detail" class="hash"></p><details><summary>Declared modules</summary><p id="modules" class="hash"></p></details><p class="muted">Turning Prebid off keeps your uploaded files and bidder settings. Future packages then use GPT only.</p><h3>Save settings for the final package</h3><label class="toggle"><input type="checkbox" id="ack"> Apply these settings to the TEST copy only.</label><p id="saved-mode" class="muted"></p><div class="actions"><button id="save-prebid" class="primary">Save Prebid settings</button></div><p class="muted">Then use Back to Generate. The selected file is checked again and included unchanged in the new ZIP. Existing ZIPs remain unchanged.</p></section></fieldset>
<div class="actions"><button id="reload-prebid">Reload saved settings</button></div><p class="muted">Reload discards unsaved edits on this page.</p></main><script src="/prebid-settings.js" defer></script></body></html>`;}
export const prebidScript = `
'use strict';
const fetchPrebidVersions = ${fetchPrebidVersions.toString()};
const el=(id)=>document.getElementById(id);let state=null,busy=false,stale=true,buildPlan=null,planTimer=null,editEpoch=0,versionsBusy=false;
function invalid(text){const error=Error(text);error.status=422;return error;}
function message(text,error=false){el('message').textContent=text;el('message').classList.toggle('error',error);}
function controls(){el('editor').disabled=busy||!state;el('reload-prebid').disabled=busy;el('save-prebid').disabled=busy||stale||!el('ack').checked;el('save-plan').disabled=busy||stale;el('load-versions').disabled=versionsBusy;el('download-config').disabled=busy||stale;el('open-builder').disabled=busy||stale;}
async function api(path,body,raw=false){const r=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:raw?{'content-type':'application/javascript','x-tessera-upload':'prebid-test-file'}:{'content-type':'application/json'},body:body===undefined?undefined:raw?body:JSON.stringify(body)});if(r.status===401){location.assign('/login');const error=Error('Please sign in again.');error.status=401;throw error;}const data=await r.json();if(!r.ok){const error=Error(data.error||'The operation could not be confirmed. Reload saved settings.');error.status=r.status;throw error;}return data;}
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function choose(values,value){const s=node('select');for(const v of values){const o=node('option',v.label??v);o.value=v.value??v;s.append(o);}s.value=value;return s;}
function field(parent,label,input){const box=node('div'),l=node('label',label);l.append(input);box.append(l);parent.append(box);return input;}
function jsonText(value){const t=node('textarea');t.value=JSON.stringify(value,null,2);return t;}
function removeButton(parent){const b=node('button','Remove');b.className='remove';b.type='button';b.addEventListener('click',()=>{parent.remove();invalidatePlan();});return b;}
function bidderRow(b={bidder:state.supportedBidders[0],params:{},enabled:true}){const row=node('div');row.className='row bidder';field(row,'Bidder',choose(state.supportedBidders,b.bidder)).dataset.field='bidder';field(row,'Partner parameters (JSON)',jsonText(b.params)).dataset.field='params';const end=node('div'),l=node('label','Enabled '),on=node('input');on.type='checkbox';on.checked=b.enabled;on.dataset.field='enabled';l.append(on);end.append(l,removeButton(row));row.append(end);el('bidders').append(row);}
function overrideRow(o={bidder:state.supportedBidders[0],scopeType:'slot',scopeKey:'ATF',params:{},enabled:true}){const row=node('div');row.className='row override';field(row,'Bidder',choose(state.supportedBidders,o.bidder)).dataset.field='bidder';const scope=field(row,'Override by',choose([{label:'ATF / BTF',value:'slot'},{label:'Device',value:'device'},{label:'Ad position',value:'adunit'}],o.scopeType));scope.dataset.field='scopeType';const target=field(row,'Target',choose([],''));target.dataset.field='scopeKey';const populate=(value)=>{target.replaceChildren();const values=scope.value==='slot'?['ATF','BTF']:scope.value==='device'?['desktop','tablet','mobile']:state.units.map(u=>u.code);values.forEach(v=>{const n=node('option',v);n.value=v;target.append(n);});if(values.includes(value))target.value=value;};populate(o.scopeKey);scope.addEventListener('change',()=>populate(''));const box=node('div');box.className='params';field(box,'Override parameters (JSON)',jsonText(o.params)).dataset.field='params';row.append(box);const l=node('label','Enabled '),on=node('input');on.type='checkbox';on.checked=o.enabled;on.dataset.field='enabled';l.append(on);row.append(l,removeButton(row));el('overrides').append(row);}
function readRows(id,override=false){return [...el(id).children].map(row=>{const get=(k)=>row.querySelector('[data-field="'+k+'"]');let params;try{params=JSON.parse(get('params').value);}catch{throw invalid('Check the JSON parameter object for '+get('bidder').value+'.');}return {bidder:get('bidder').value,params,enabled:get('enabled').checked,...(override?{scopeType:get('scopeType').value,scopeKey:get('scopeKey').value}:{})};});}
function detail(){const f=state?.files.find(f=>f.id===el('build').value);el('file-detail').textContent=f?f.version+' · SHA-256 '+f.sha256:'No saved file selected.';el('modules').textContent=f?f.modules.join(', '):'—';}
function files(selected){el('build').replaceChildren();const blank=node('option','Choose an uploaded file');blank.value='';if(state.draft.buildId)blank.disabled=true;el('build').append(blank);for(const file of state.files){const o=node('option',file.version+' · '+file.sha256.slice(0,12)+(file.id===state.draft.buildId?' · saved choice':''));o.value=file.id;el('build').append(o);}el('build').value=selected||'';detail();}
async function load(success){state=await api('/test-api/prebid-settings');stale=false;el('site').textContent=state.site.name+' · TEST copy';const draft=state.plan?.draft||state.draft;el('enable-prebid').checked=draft.enablePrebid;files(draft.buildId);el('bidders').replaceChildren();draft.bidders.forEach(bidderRow);el('overrides').replaceChildren();draft.overrides.forEach(overrideRow);fillOptions(state.plan?.options||state.options);el('plan-version').value=state.plan?.version||state.version;el('ack').checked=false;el('saved-mode').textContent='Saved mode: '+(state.draft.enablePrebid?'Prebid enabled':'GPT only')+'. Required modules for the saved configuration: '+(state.requiredModules.join(', ')||'none while Prebid is off')+'.';message(success||state.validationIssue||(state.plan?'Saved preparation restored. The active selection stays in place until Save Prebid settings.':'Set bidders and options, then download prebid-config.json.'),!!state.validationIssue);invalidatePlan();loadVersions();}
async function action(fn,{writes=true}={}){if(busy)return;busy=true;controls();try{await fn();}catch(e){if(e.status===409||(writes&&(!e.status||e.status>=500)))stale=true;message(e.message,true);}finally{busy=false;controls();}}
el('upload').addEventListener('click',()=>action(async()=>{const file=el('upload-file').files[0];if(!file||!file.size)throw invalid('Select a non-empty Prebid.js file.');if(file.size>8*1024*1024)throw invalid('Prebid.js must be no larger than 8 MiB.');const selected=el('build').value;const r=await api('/test-api/prebid/upload',file,true);const fresh=await api('/test-api/prebid-settings');state.files=fresh.files;files(selected);el('upload-file').value='';if(fresh.revision!==state.revision){stale=true;message('File stored, but settings changed in another tab. Reload before saving.',true);}else {message(r.created?'File stored. Choose it from Saved file and save your settings.':'This exact file is already stored. No duplicate was created.');invalidatePlan();}}));
el('add-bidder').addEventListener('click',()=>{bidderRow();invalidatePlan();});el('add-override').addEventListener('click',()=>{overrideRow();invalidatePlan();});el('build').addEventListener('change',()=>{detail();invalidatePlan();});el('ack').addEventListener('change',controls);
el('save-prebid').addEventListener('click',()=>action(async()=>{if(stale)return;const r=await api('/test-api/prebid-settings',{...planRequest(),acknowledge:el('ack').checked});await load(r.changed?'Prebid settings saved. Back to Generate uses this exact selection.':'These settings were already saved. No duplicate was created.');}));
function fillOptions(options){el('floors-enabled').checked=options.floorsEnabled;el('hard-floor').value=options.hardFloor;el('currency').value=options.currency;el('currency-conversion').checked=options.currencyConversionEnabled;el('user-ids').replaceChildren();for(const id of state.userIds){const value=options.userIds.find(r=>r.name===id.name),row=node('div');row.dataset.name=id.name;const label=node('label',id.label+' '),on=node('input');on.type='checkbox';on.checked=value.enabled;on.dataset.field='enabled';label.append(on);row.append(label);const t=jsonText(value.settings);t.dataset.field='settings';field(row,'Partner settings (JSON)',t);el('user-ids').append(row);}}
function planRequest(){return {expectedRevision:state.revision,version:el('plan-version').value.trim(),draft:{enablePrebid:el('enable-prebid').checked,buildId:el('build').value||null,bidders:readRows('bidders'),overrides:readRows('overrides',true)},options:{floorsEnabled:el('floors-enabled').checked,hardFloor:Number(el('hard-floor').value),currency:el('currency').value.trim().toUpperCase(),currencyConversionEnabled:el('currency-conversion').checked,userIds:[...el('user-ids').children].map(row=>{let settings;try{settings=JSON.parse(row.querySelector('[data-field="settings"]').value);}catch{throw invalid('Check the JSON settings for '+row.dataset.name+'.');}return {name:row.dataset.name,enabled:row.querySelector('[data-field="enabled"]').checked,settings};})}};}
function showPlan(plan){buildPlan=plan;el('plan-modules').replaceChildren(...plan.modules.map(m=>node('p',m.reason+' → '+m.name)));const file=state.files.find(f=>f.id===el('build').value);let text=plan.configuration.modules.length+' modules selected automatically.';if(file){const missing=plan.configuration.modules.filter(m=>!file.modules.includes(m));if(file.version!==plan.version)text+=' Selected file version '+file.version+' differs from planned '+plan.version+'.';if(missing.length)text+=' New build needed. Missing: '+missing.join(', ')+'.';if(!missing.length&&file.version===plan.version)text+=' Selected file declares the required version and modules. Save verifies its original bytes.';}else text+=' No Prebid file is needed to download this configuration.';el('plan-state').textContent=text;}
function invalidatePlan(){buildPlan=null;editEpoch++;clearTimeout(planTimer);el('plan-state').textContent='Options changed. Updating the required modules…';el('plan-modules').replaceChildren();const epoch=editEpoch;planTimer=setTimeout(async()=>{if(!state||stale)return;try{const p=await api('/test-api/prebid/plan',planRequest());if(epoch===editEpoch)showPlan(p);}catch(e){if(epoch!==editEpoch)return;el('plan-state').textContent=e.message;if(e.status===409){stale=true;controls();}}},350);}
async function freshPlan(){clearTimeout(planTimer);editEpoch++;const p=await api('/test-api/prebid/plan',planRequest());showPlan(p);return p;}
// Catalog reads never acquire the mutation lock or change the form's revision.
async function loadVersions(){
  if(versionsBusy)return;versionsBusy=true;controls();el('version-note').textContent='Checking available versions… You can keep working.';
  try{
    let data;
    try{data=await api('/test-api/prebid/versions');}
    catch(error){if(error.status===401)throw error;data=await fetchPrebidVersions();}
    const select=el('available-versions');select.replaceChildren(node('option','Choose a version for the new build'));select.firstChild.value='';
    for(const v of data.versions){const o=node('option',v);o.value=v;select.append(o);}
    const offered=data.versions.includes(el('plan-version').value);
    el('version-note').textContent=offered?'Version list ready. Your chosen version is available.':'Prebid no longer offers the entered version. Choose another version for the new build; your saved file stays in place.';
    if(!offered)el('version-options').open=true;
  }catch(error){
    el('version-note').textContent='Version list unavailable. You can still save and download with the version above, or check versions in Prebid.';
  }finally{versionsBusy=false;controls();}
}
el('load-versions').addEventListener('click',loadVersions);
el('available-versions').addEventListener('change',()=>{if(el('available-versions').value){el('plan-version').value=el('available-versions').value;el('version-note').textContent='Version chosen for the new build. The active file stays unchanged until Save Prebid settings.';invalidatePlan();}});
el('editor').addEventListener('input',e=>{if(!['ack','upload-file'].includes(e.target.id))invalidatePlan();});
async function persistPreparation(){
  clearTimeout(planTimer);editEpoch++;
  const r=await api('/test-api/prebid/plan/save',{...planRequest(),acknowledge:true});
  state.revision=r.revision;state.plan=r.plan;showPlan(r.plan);return r.plan;
}
el('download-config').addEventListener('click',()=>action(async()=>{
  const p=await persistPreparation(),blob=new Blob([JSON.stringify(p.configuration,null,2)+'\\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');
  a.href=url;a.download='prebid-config.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);
  message('Preparation saved and prebid-config.json downloaded. Next: Open Prebid builder → Upload Configuration.');
}));
el('open-builder').addEventListener('click',()=>{
  if(busy||stale)return;
  const tab=window.open('about:blank','_blank');
  if(!tab){message('Allow a new tab for Prebid, then click Open Prebid builder.',true);return;}
  tab.opener=null;
  action(async()=>{try{const p=await freshPlan();tab.location.replace(p.builderUrl);}catch(error){tab.close();throw error;}},{writes:false});
});
el('save-plan').addEventListener('click',()=>action(async()=>{await persistPreparation();message('Build preparation saved. Your active Prebid choice and generated packages are unchanged.');}));
el('reload-prebid').addEventListener('click',()=>action(()=>load()));action(()=>load());
`;
