import assert from 'node:assert/strict';
import test from 'node:test';
import { formatMinimumHeightCss } from '../../src/export/min-height-css.ts';
import { placeholderStyles } from '../../worker/runtime/artifact-styles.mjs';

test('groups existing generated placeholders by viewport and height', () => {
  const result = formatMinimumHeightCss(placeholderStyles({
    options: { sticky: { bottomAdUnitId: 'Sticky' } },
    core: {
      explicitUnits: [
        { id: 'Billboard', sizeMapName: 'billboard' },
        { id: 'P1', sizeMapName: 'rectangle' },
        { id: 'P2', sizeMapName: 'rectangle' },
        { id: 'Sticky', sizeMapName: 'rectangle' },
        { id: 'Branding_Left', sizeMapName: 'branding' },
      ],
      sizeMapsRaw: {
        billboard: [
          { viewport: [0, 0], sizes: [[320, 100]] },
          { viewport: [469, 0], sizes: [[468, 60], [320, 100]] },
          { viewport: [768, 0], sizes: [[750, 200]] },
          { viewport: [1024, 0], sizes: [[970, 250]] },
        ],
        rectangle: [
          { viewport: [0, 0], sizes: [[300, 250]] },
          { viewport: [768, 0], sizes: [[300, 600]] },
        ],
        branding: [
          { viewport: [0, 0], sizes: [] },
          { viewport: [1300, 0], sizes: [[160, 600]] },
        ],
      },
    },
  }));
  assert.equal(result, `/* Generated responsive placeholders; sticky and TakeOver are excluded. */

/* 0–468px */
#Branding_Left { min-height: 0px; }

#Billboard { min-height: 100px; }

#P1, #P2 { min-height: 250px; }

/* >= 469px */
@media (min-width: 469px) {
  #Billboard { min-height: 100px; }
}

/* >= 768px */
@media (min-width: 768px) {
  #Billboard { min-height: 200px; }

  #P1, #P2 { min-height: 600px; }
}

/* >= 1024px */
@media (min-width: 1024px) {
  #Billboard { min-height: 250px; }
}

/* >= 1300px */
@media (min-width: 1300px) {
  #Branding_Left { min-height: 600px; }
}
`);
  assert.equal(formatMinimumHeightCss(result), result);
});

test('retains zero-height resets and escaped IDs at higher breakpoints', () => {
  const result = formatMinimumHeightCss('#ad\\:one{min-height:0;}\n#ad\\:one{min-height:250px;}\n@media(min-width:768px){#ad\\:one{min-height:0px;}}');
  assert.equal(result, '/* 0–767px */\n#ad\\:one { min-height: 250px; }\n\n/* >= 768px */\n@media (min-width: 768px) {\n  #ad\\:one { min-height: 0px; }\n}\n');
});

test('supports already grouped legacy CSS and a stylesheet without breakpoints', () => {
  const result = formatMinimumHeightCss('/* Generated by Prebid Professor. */\n/* 0px and above */\n#A, #B { min-height: 250px; }\n#C { min-height: 100px; }');
  assert.equal(result, '/* Generated by Prebid Professor. */\n\n/* >= 0px */\n#C { min-height: 100px; }\n\n#A, #B { min-height: 250px; }\n');
});

test('leaves custom CSS and unsafe cascade orders unchanged', () => {
  for (const css of [
    '', '/* no positions */',
    '#A { min-height: 250px; display: none; }',
    '.ad { min-height: 250px; }',
    '#A { min-height: 250px !important; }',
    '@media (max-width: 768px) { #A { min-height: 250px; } }',
    '@media (min-width: 768px) { #A { min-height: 600px; } } #A { min-height: 250px; }',
    '@media (min-width: 768px) { #A { min-height: 600px; }',
    '#A{min-height:250px;} @supports(display:grid){#A{min-height:0;}}',
  ]) assert.equal(formatMinimumHeightCss(css), css);
});
