import test from 'node:test';
import assert from 'node:assert/strict';
import { initializeTestSchema } from '../../worker/test-workspace/schema.mjs';
import { workspaceStore } from '../support/test-workspace-store.mjs';
import { readSiteDraft, normalizeSiteDraft, planSiteDraft, assertWorkspaceSiteScope } from '../../worker/test-workspace/site-draft.mjs';
import { commitSiteDraft } from '../../worker/test-workspace/site-draft-store.mjs';
import { commitTestRuntimeSelection } from '../../worker/test-workspace/selection-transaction.mjs';
import { digest } from '../../worker/runtime/preview-snapshot.mjs';
const active=[];
test.afterEach(()=>{while(active.length)active.pop().sqlite.close();});
async function fixture(){const x=workspaceStore();active.push(x);await initializeTestSchema(x.env.DB,'tester@example.invalid');
 const sql=x.sqlite,config=JSON.parse(sql.prepare("SELECT config_json FROM publisher_configs WHERE publisher_id='test-site'").get().config_json);
 config.builtinRuntimeSelection={schemaVersion:1};config.unrelated={keep:'unchanged'};
 sql.prepare("UPDATE publisher_configs SET config_json=? WHERE publisher_id='test-site'").run(JSON.stringify(config));
 const select=(table,cols,single=false,order='')=>{const v=sql.prepare(`SELECT ${cols} FROM ${table} WHERE ${table==='publishers'?'id':'publisher_id'}=? ${order}`).all('test-site').map(r=>({...r}));return single?v[0]:v;};
 x.snapshot=()=>({site:select('publishers','id,name,domain,gam_path',true),config:select('publisher_configs','config_json',true),
 units:select('ad_units','code,type,media_type,size_map_key,enabled,sort_order',false,'ORDER BY sort_order,code'),bidders:select('bidders','bidder,params_json,enabled',false,'ORDER BY bidder'),
 overrides:select('bidder_overrides','bidder,scope_type,scope_key,params_json,enabled',false,'ORDER BY bidder,scope_type,scope_key'),maps:select('size_maps','name,map_json',false,'ORDER BY name'),rules:select('unit_rules','rule_key,rule_json',false,'ORDER BY rule_key'),
 prebidBuilds:select('prebid_builds','id,publisher_id,version,file_key,modules_json,status,uploaded_at',false,"AND status='current' ORDER BY uploaded_at DESC,id LIMIT 2")});
 x.plan=async(draft=readSiteDraft(x.snapshot()),before=x.snapshot())=>planSiteDraft(before,{expectedRevision:await digest(before),acknowledge:true,draft});
 x.save=(plan)=>commitSiteDraft({isolation:'explicit-test-store',db:x.env.DB},plan,'tester@example.invalid');
 x.audit=()=>sql.prepare("SELECT COUNT(*) n FROM audit_log WHERE action='test_workspace.site_draft_saved'").get().n;
 return x;}
const copy=(v)=>structuredClone(v);
for(const [name,change] of [
  ['invalid enabled',t=>t.enabled='yes'],['empty code',t=>t.adUnitCode=''],['unsafe code',t=>t.adUnitCode='../../other'],['fallback collision',t=>t.adUnitCode='Interstitial'],['position collision',t=>t.adUnitCode='Billboard'],['bad desktop width',t=>t.desktopMinWidth=0],['zero size',t=>t.desktopSize=[0,600]],['invalid size',t=>t.mobileSize=[300.5,250]],['negative timer',t=>t.autoCloseDesktopSec=-1],['too long timer',t=>t.autoCloseMobileSec=301],['invalid countdown',t=>t.showCountdown=null],['unknown option',t=>t.source='code']
])test('TakeOver rejects '+name,async()=>{const x=await fixture(),d=readSiteDraft(x.snapshot());change(d.takeOver);assert.throws(()=>normalizeSiteDraft(d));assert.equal(x.audit(),0);});
test('invalid persisted TakeOver is reported without replacing it with defaults',async()=>{const x=await fixture(),s=x.snapshot(),c=JSON.parse(s.config.config_json);c.runtimeControls??={};c.runtimeControls.takeOver=null;s.config.config_json=JSON.stringify(c);assert.throws(()=>readSiteDraft(s),/Saved TakeOver settings need review/);assert.equal(JSON.parse(s.config.config_json).runtimeControls.takeOver,null);});
test('site draft is a strict editable projection, not raw saved configuration',async()=>{const x=await fixture(),d=readSiteDraft(x.snapshot());assert.equal(d.site.domain,'example.invalid');assert.equal(d.units.length,2);assert(!JSON.stringify(d).includes('unrelated'));assert.equal(d.maps[0].breakpoints[0].minWidth,0);});
test('full draft edits save atomically without overwriting non-editor fields',async()=>{const x=await fixture(),before=x.snapshot(),d=readSiteDraft(before);d.site={name:'Pilot copy',domain:'news.example.invalid',gamPath:'123/pilot'};d.units.push({code:'InText1',type:'BTF',sizeMap:'display',enabled:true});d.maps[0].breakpoints.push({minWidth:768,sizes:[[728,90]]});const plan=await x.plan(d);const r=await x.save(plan);assert.deepEqual(r,{persisted:true,changed:true,publishable:false});assert.deepEqual(x.snapshot(),plan.after);assert.equal(x.snapshot().site.gam_path,'/123/pilot/');assert.equal(JSON.parse(x.snapshot().config.config_json).unrelated.keep,'unchanged');assert.equal(x.audit(),1);assert.equal(x.log.puts.length,0);});
test('site edit does not alter existing notes or record IDs for retained rows',async()=>{const x=await fixture();x.sqlite.exec("UPDATE ad_units SET notes='keep' WHERE code='Billboard'");const ids=x.sqlite.prepare('SELECT id,code,created_at,notes FROM ad_units ORDER BY code').all();await x.save(await x.plan());assert.deepEqual(x.sqlite.prepare('SELECT id,code,created_at,notes FROM ad_units ORDER BY code').all(),ids);});
test('repeat save of the same normalized draft is a no-op',async()=>{const x=await fixture();await x.save(await x.plan());const before=x.snapshot();const r=await x.save(await x.plan());assert.equal(r.changed,false);assert.equal(x.audit(),1);assert.deepEqual(x.snapshot(),before);});
test('deleting one position and an unused map touches only that TEST copy',async()=>{const x=await fixture();x.sqlite.exec("INSERT INTO publishers(id,name,domain,gam_path) VALUES('other','Other','other.invalid','/123/other/'); INSERT INTO ad_units(id,publisher_id,code,type) VALUES('other-unit','other','OtherUnit','ATF'); INSERT INTO size_maps(id,publisher_id,name) VALUES('other-map','other','other')");const d=readSiteDraft(x.snapshot());d.units=d.units.filter(u=>u.code!=='Sticky');d.maps=d.maps.filter(m=>m.name!=='sticky');d.bottomStickyId='';await x.save(await x.plan(d));assert.equal(x.snapshot().units.length,1);assert.equal(x.snapshot().maps.length,1);assert.equal(x.sqlite.prepare("SELECT COUNT(*) n FROM ad_units WHERE publisher_id='other'").get().n,1);assert.equal(x.sqlite.prepare("SELECT COUNT(*) n FROM size_maps WHERE publisher_id='other'").get().n,1);});
test('size maps preserve deliberately empty mobile sizes and fluid sizes',async()=>{const x=await fixture(),d=readSiteDraft(x.snapshot());d.maps[0].breakpoints[0].sizes=[];d.maps[0].breakpoints[1].sizes=['fluid',[970,250]];await x.save(await x.plan(d));assert.deepEqual(readSiteDraft(x.snapshot()).maps[0].breakpoints,d.maps[0].breakpoints);});
test('edited site is accepted only with a saved runtime and explicit TEST draft marker',async()=>{const x=await fixture();const d=readSiteDraft(x.snapshot());d.site.domain='publisher.example';d.site.gamPath='/23339552141/Pilot/';const p=await x.plan(d);assert.doesNotThrow(()=>assertWorkspaceSiteScope(p.after));for(const marker of [false,true]){const s=copy(p.after),c=JSON.parse(s.config.config_json);if(marker)delete c.builtinRuntimeSelection;else delete c.testSiteDraft;s.config.config_json=JSON.stringify(c);assert.throws(()=>assertWorkspaceSiteScope(s));}});
test('new draft requires an explicitly saved script version',async()=>{const x=await fixture(),s=x.snapshot(),c=JSON.parse(s.config.config_json);delete c.builtinRuntimeSelection;s.config.config_json=JSON.stringify(c);await assert.rejects(x.plan(readSiteDraft(s),s),/exact script version/);});
test('unsupported height-based maps cannot be silently converted',async()=>{const x=await fixture(),s=x.snapshot();s.maps[0].map_json='[{"viewport":[0,100],"sizes":[[300,250]]}]';assert.throws(()=>readSiteDraft(s),/width-based/);});
test('removing a position with saved per-position rules is rejected',async()=>{const x=await fixture();x.sqlite.exec("INSERT INTO unit_rules(id,publisher_id,rule_key,rule_json) VALUES('custom','test-site','Sticky','{}')");const d=readSiteDraft(x.snapshot());d.units=d.units.filter(u=>u.code!=='Sticky');d.bottomStickyId='';await assert.rejects(x.plan(d),/still has saved rules/);});
const invalid=[['extra root',d=>d.source='bad'],['extra site',d=>d.site.id='politika'],['URL domain',d=>d.site.domain='https://politika.rs/path'],['port domain',d=>d.site.domain='news.example:8080'],['domain script',d=>d.site.domain='<script>'],['empty name',d=>d.site.name=' '],['path traversal',d=>d.site.gamPath='/123/../'],['path query',d=>d.site.gamPath='/123/site/?x=y'],['network ID',d=>d.site.gamPath='/abc/site/'],['duplicate position',d=>d.units.push(copy(d.units[0]))],['unsafe ID',d=>d.units[0].code='Billboard > div'],['prototype ID',d=>d.units[0].code='constructor'],['TakeOver as position',d=>d.units[0].code='TakeOver'],['bad type',d=>d.units[0].type='VIDEO'],['bad enabled',d=>d.units[0].enabled=1],['missing map',d=>d.units[0].sizeMap='missing'],['all disabled',d=>d.units.forEach(u=>u.enabled=false)],['missing sticky',d=>d.bottomStickyId='NotDefined'],['duplicate map',d=>d.maps.push(copy(d.maps[0]))],['duplicate width',d=>d.maps[0].breakpoints.push(copy(d.maps[0].breakpoints[0]))],['missing base',d=>d.maps[0].breakpoints.shift()],['bad width',d=>d.maps[0].breakpoints[0].minWidth=-1],['fractional size',d=>d.maps[0].breakpoints[0].sizes=[[300.5,250]]],['zero size',d=>d.maps[0].breakpoints[0].sizes=[[0,250]]],['duplicate size',d=>d.maps[0].breakpoints[0].sizes=[[300,250],[300,250]]],['all sizes empty',d=>d.maps[0].breakpoints.forEach(r=>r.sizes=[])],['too many units',d=>d.units=Array.from({length:101},(_,i)=>({...d.units[0],code:'Ad'+i}))]];
for(const[name,change]of invalid)test('rejects '+name,async()=>{const x=await fixture(),d=readSiteDraft(x.snapshot());change(d);assert.throws(()=>normalizeSiteDraft(d));assert.equal(x.audit(),0);});
const races=[['name',"UPDATE publishers SET name='newer' WHERE id='test-site'"],['config',"UPDATE publisher_configs SET config_json='{}' WHERE publisher_id='test-site'"],['unit',"UPDATE ad_units SET enabled=0 WHERE code='Billboard'"],['map',"UPDATE size_maps SET map_json='[]' WHERE name='display'"],['rule',"UPDATE unit_rules SET rule_json='{}' WHERE rule_key='__DEFAULT__'"],['bidder',"INSERT INTO bidders(id,publisher_id,bidder) VALUES('b','test-site','ix')"],['build',"INSERT INTO prebid_builds(id,publisher_id,version,file_key,status) VALUES('pb','test-site','1.0.0','key','current')"]];
for(const[name,sql]of races)test('atomic stale '+name+' prevents overwriting newer edits',async()=>{const x=await fixture(),p=await x.plan();x.sqlite.exec(sql);await assert.rejects(x.save(p),{code:'configuration_changed',status:409});assert.equal(x.audit(),0);});
test('two simultaneous drafts cannot overwrite each other',async()=>{const x=await fixture(),p=await x.plan();const results=await Promise.allSettled([x.save(p),x.save(p)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected')[0].reason.status,409);});
test('a stale runtime selection cannot overwrite new positions',async()=>{const x=await fixture(),before=x.snapshot(),p=await x.plan();await x.save(p);await assert.rejects(commitTestRuntimeSelection({isolation:'explicit-test-store',db:x.env.DB},{snapshot:before,configJson:before.config.config_json,actor:'tester'}),{code:'configuration_changed'});});
for(let index=0;index<10;index++)test('failure at write statement '+index+' rolls the whole draft back',async()=>{const x=await fixture(),p=await x.plan(),before=x.snapshot();x.faults.batchAt=index;await assert.rejects(x.save(p),{code:'save_unconfirmed'});assert.deepEqual(x.snapshot(),before);assert.equal(x.audit(),0);});
test('lost commit response is recovered by reload without duplicate audit',async()=>{const x=await fixture(),p=await x.plan();const orig=x.env.DB.batch;x.env.DB.batch=async(rows)=>{await orig(rows);throw Error('private failure');};await assert.rejects(x.save(p),{code:'save_unconfirmed'});assert.deepEqual(x.snapshot(),p.after);x.env.DB.batch=orig;assert.equal((await x.save(await x.plan())).changed,false);assert.equal(x.audit(),1);});
test('source/snapshot mutation after first await cannot change the proposal',async()=>{const x=await fixture(),s=x.snapshot(),d=readSiteDraft(s),revision=await digest(s);const promise=planSiteDraft(s,{draft:d,expectedRevision:revision,acknowledge:true});s.site.name='mutated';d.units[0].code='mutated';const p=await promise;assert.equal(p.after.site.name,'Tessera demo');assert.equal(p.after.units[0].code,'Billboard');});
test('100 positions and 32 maps still use a constant 10-statement transaction',async()=>{const x=await fixture(),d=readSiteDraft(x.snapshot());d.units=Array.from({length:100},(_,i)=>({code:'Ad'+i,type:'BTF',sizeMap:'map'+(i%32),enabled:true}));d.maps=Array.from({length:32},(_,i)=>({name:'map'+i,breakpoints:[{minWidth:0,sizes:[[300,250]]}]}));d.bottomStickyId='';const p=await x.plan(d);let count;const orig=x.env.DB.batch;x.env.DB.batch=async(rows)=>{count=rows.length;return orig(rows);};await x.save(p);assert.equal(count,10);assert.equal(x.snapshot().units.length,100);});

test('null sticky selection remains OFF instead of inheriting the Sticky unit',async()=>{
  const x=await fixture(),c=JSON.parse(x.snapshot().config.config_json);c.runtimeControls??={};c.runtimeControls.sticky??={};c.runtimeControls.sticky.bottomAdUnitId=null;
  x.sqlite.prepare("UPDATE publisher_configs SET config_json=? WHERE publisher_id='test-site'").run(JSON.stringify(c));
  const d=readSiteDraft(x.snapshot());assert.equal(d.bottomStickyId,'');d.site.name='Other setting';await x.save(await x.plan(d));assert.equal(readSiteDraft(x.snapshot()).bottomStickyId,'');
});
