import test from 'node:test';
import assert from 'node:assert/strict';
import { unzipSync } from 'fflate';
import worker from '../../worker/test-workspace/index.mjs';
import { workspaceStore,ORIGIN,TEST_EMAIL,TEST_PASSWORD } from '../support/test-workspace-store.mjs';
const active=[],originalFetch=globalThis.fetch;
const bytes=new TextEncoder().encode('/* prebid.js v11.11.0\nModules: adformBidAdapter, consentManagementTcf, tcfControl, currency */\nwindow.fixtureOnly=true;');
test.before(()=>{globalThis.fetch=()=>assert.fail('No actual ad or publisher network calls');});test.after(()=>{globalThis.fetch=originalFetch;});test.afterEach(()=>{while(active.length)active.pop().close();});
async function request(f,path,cookie,body,raw=false,origin=ORIGIN){const r=await worker.fetch(new Request(ORIGIN+path,{method:body===undefined?'GET':'POST',headers:{...(cookie?{cookie}:{}),...(body===undefined?{}:{origin,...(raw?{'content-type':'application/javascript','x-tessera-upload':'prebid-test-file'}:{'content-type':'application/json'})})},body:body===undefined?undefined:raw?body:JSON.stringify(body)}),f.env);return {r,data:r.headers.get('content-type')?.includes('json')?await r.json():null};}
async function ready(){const f=workspaceStore({prebidFiles:true});active.push(f);const login=await worker.fetch(new Request(ORIGIN+'/api/auth/login',{method:'POST',headers:{origin:ORIGIN,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({email:TEST_EMAIL,password:TEST_PASSWORD})}),f.env);const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await request(f,'/test-api/setup',cookie,{confirm:'prepare-empty-test-database'})).r.status,200);const s=(await request(f,'/test-api/runtime-selection',cookie)).data;assert.equal((await request(f,'/test-api/runtime-selection',cookie,{expectedRevision:s.revision,selection:{runtime:s.runtimes[0].pin,allowPreview:true,enablePrebid:false,prebidBuildId:null}})).r.status,200);return {f,cookie};}
const state=async(f,c)=>(await request(f,'/test-api/prebid-settings',c)).data;
async function enable(f,c,file=bytes){const u=await request(f,'/test-api/prebid/upload',c,file,true);assert.equal(u.r.status,200,JSON.stringify(u.data));const s=await state(f,c);const body={expectedRevision:s.revision,acknowledge:true,draft:{...s.draft,enablePrebid:true,buildId:u.data.file.id,bidders:[{bidder:'adform',params:{mid:123},enabled:true}]}};const r=await request(f,'/test-api/prebid-settings',c,body);assert.equal(r.r.status,200,JSON.stringify(r.data));return body;}
async function generate(f,c){const x=await request(f,'/test-api/generate',c,{acknowledge:true,takeOverEnabled:true});assert.equal(x.r.status,200,JSON.stringify(x.data));return x.data;}
test('new page and JS require session, new upload/API refuse unauthenticated before storage access',async()=>{const f=workspaceStore({prebidFiles:true});active.push(f);Object.defineProperty(f.env,'DB',{get(){assert.fail('No database before session');}});for(const p of ['/prebid-settings','/prebid-settings.js'])assert.equal((await request(f,p)).r.status,303);for(const [p,b,r] of [['/test-api/prebid-settings',undefined,false],['/test-api/prebid-settings',{},false],['/test-api/prebid/upload',bytes,true]])assert.equal((await request(f,p,null,b,r)).r.status,401);});
test('cross-origin upload is refused before any DB or R2 read',async()=>{const{f,cookie}=await ready();Object.defineProperty(f.env,'DB',{get(){assert.fail('No DB before origin validation');}});assert.equal((await request(f,'/test-api/prebid/upload',cookie,bytes,true,'https://evil.invalid')).r.status,403);});
test('new page uses restrictive CSP, own script and no executable ad library',async()=>{const{f,cookie}=await ready();const{r}=await request(f,'/prebid-settings',cookie);assert.equal(r.status,200);const h=await r.text();assert(h.includes('/prebid-settings.js'));assert(!h.includes('gpt.js'));assert(!h.includes('src="./prebid.js"'));assert.match(r.headers.get('content-security-policy'),/default-src 'none'/);assert.match(r.headers.get('content-security-policy'),/connect-src 'self' https:\/\/js-download\.prebid\.org\/versions;/);assert(!((await request(f,'/site-settings',cookie)).r.headers.get('content-security-policy')).includes('js-download.prebid.org'));assert.equal((await request(f,'/prebid-settings.js',cookie)).r.status,200);});
test('upload alone preserves selected settings and produces no candidate/release',async()=>{const{f,cookie}=await ready(),s=await state(f,cookie),u=await request(f,'/test-api/prebid/upload',cookie,bytes,true);assert.equal(u.r.status,200,JSON.stringify(u.data));const next=await state(f,cookie);assert.equal(next.revision,s.revision);assert.equal(next.draft.enablePrebid,false);assert.equal(next.files.length,1);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM releases').get().n,0);});
test('real HTTP upload -> enable -> Generate -> Save -> download includes identical original prebid.js',async()=>{const{f,cookie}=await ready();await enable(f,cookie);const g=await generate(f,cookie);assert.equal(g.descriptor.files.length,10);const saved=await request(f,'/test-api/save',cookie,{receipt:g.receipt,acknowledge:true,note:'Prebid test'});assert.equal(saved.r.status,200,JSON.stringify(saved.data));const r=await request(f,'/test-api/releases/'+saved.data.draft.id+'/download',cookie);const z=unzipSync(new Uint8Array(await r.r.arrayBuffer()));assert.deepEqual(z['prebid.js'],bytes);const config=JSON.parse(new TextDecoder().decode(z['config.json']));assert.equal(config.options.enablePrebid,true);assert.deepEqual(config.core.bidders,[{bidder:'adform',params:{mid:123}}]);assert.equal(config.options.takeOver.enabled,true);});
test('replacement changes only new generation, old saved ZIP stays byte-identical, old receipt becomes stale',async()=>{const{f,cookie}=await ready();await enable(f,cookie);const g=await generate(f,cookie),saved=await request(f,'/test-api/save',cookie,{receipt:g.receipt,acknowledge:true,note:''});const path='/test-api/releases/'+saved.data.draft.id+'/download';const original=new Uint8Array(await(await request(f,path,cookie)).r.arrayBuffer());await enable(f,cookie,new TextEncoder().encode(new TextDecoder().decode(bytes)+'\n// v2 bytes'));assert.equal((await request(f,'/test-api/save',cookie,{receipt:g.receipt,acknowledge:true,note:''})).r.status,409);assert.deepEqual(new Uint8Array(await(await request(f,path,cookie)).r.arrayBuffer()),original);});
test('turn off retains bidders/file and generates GPT-only nine-file package',async()=>{const{f,cookie}=await ready();await enable(f,cookie);const s=await state(f,cookie);const off=await request(f,'/test-api/prebid-settings',cookie,{expectedRevision:s.revision,acknowledge:true,draft:{...s.draft,enablePrebid:false}});assert.equal(off.r.status,200,JSON.stringify(off.data));const g=await generate(f,cookie);assert.equal(g.descriptor.files.length,9);assert.equal((await state(f,cookie)).draft.bidders.length,1);});
test('tampered selected file stops generation without resetting settings or repairing bytes',async()=>{const{f,cookie}=await ready();await enable(f,cookie);const key=[...f.objects.keys()][0];f.objects.get(key)[0]^=1;const g=await request(f,'/test-api/generate',cookie,{acknowledge:true,takeOverEnabled:false});assert.equal(g.r.status,422);assert.equal(JSON.parse(f.sqlite.prepare('SELECT config_json FROM publisher_configs').get().config_json).enablePrebid,true);});
test('extra raw source/config/site/URL fields and query routes are rejected',async()=>{const{f,cookie}=await ready(),s=await state(f,cookie);for(const extra of [{siteId:'politika'},{source:'javascript'},{configJson:'{}'},{url:'https://example.invalid/prebid.js'}])assert.equal((await request(f,'/test-api/prebid-settings',cookie,{expectedRevision:s.revision,acknowledge:true,draft:s.draft,...extra})).r.status,422);assert.equal((await request(f,'/test-api/prebid/upload?site=politika',cookie,bytes,true)).r.status,404);assert.equal((await request(f,'/test-api/prebid-settings?site=politika',cookie)).r.status,404);});
test('large and malformed uploads fail without registration',async()=>{const{f,cookie}=await ready();assert.equal((await request(f,'/test-api/prebid/upload',cookie,new Uint8Array(8*1024*1024+1),true)).r.status,413);assert.equal((await request(f,'/test-api/prebid/upload',cookie,new TextEncoder().encode('<html>Error</html>'),true)).r.status,422);assert.equal((await state(f,cookie)).files.length,0);});
