import test from 'node:test';
import assert from 'node:assert/strict';
import { workspaceStore } from '../support/test-workspace-store.mjs';
import { initializeTestSchema } from '../../worker/test-workspace/schema.mjs';
import { readRuntimeSelectionSettings, saveRuntimeSelectionSettings, selectedWorkspaceRuntime } from '../../worker/test-workspace/runtime-selection.mjs';
import { readPreviewSnapshot } from '../../worker/runtime/builtin-preview-service.mjs';
import { buildArtifactCandidate } from '../../worker/test-workspace/runtime-catalog.mjs';
import { readPrebidUpload,storePrebidFile,listPrebidFiles,readPrebidFile,inspectUpload,MAX_PREBID_UPLOAD } from '../../worker/test-workspace/prebid-files.mjs';
import { getPrebidSettings,preparePrebidSettings,commitPrebidSettings,savePrebidSettings,prebidStore } from '../../worker/test-workspace/prebid-settings.mjs';
import { normalizePrebidDraft } from '../../worker/test-workspace/prebid-draft.mjs';
import { getSiteDraft,saveSiteDraft } from '../../worker/test-workspace/site-draft-service.mjs';
import { generatedLiteral } from '../support/generated-literal.mjs';
import { digest } from '../../worker/runtime/preview-snapshot.mjs';
const modules=['consentManagementTcf','tcfControl','currency','adformBidAdapter'];
const file=(extra='',names=modules)=>new TextEncoder().encode(`/* prebid.js v11.11.0\nModules: ${names.join(', ')} */\nwindow.prebidFixtureOnly=true; // ${extra}\n`);
const active=[];const actor='tester@example.invalid';
test.before(()=>{globalThis.fetch=()=>assert.fail('No external fetches');});
test.afterEach(()=>{while(active.length)active.pop().close();});
async function ready(){const f=workspaceStore({prebidFiles:true});active.push(f);await initializeTestSchema(f.env.DB,actor);const s=await readRuntimeSelectionSettings(f.env);await saveRuntimeSelectionSettings(f.env,actor,{expectedRevision:s.revision,selection:{runtime:s.runtimes[0].pin,allowPreview:true,enablePrebid:false,prebidBuildId:null}});f.store=prebidStore(f.env);return f;}
const read=(f)=>getPrebidSettings(f.env);
async function upload(f,bytes=file()){return storePrebidFile(f.store,bytes,actor);}
async function proposal(f,bytes=file()){const uploaded=await upload(f,bytes),s=await read(f);return {expectedRevision:s.revision,acknowledge:true,draft:{...s.draft,enablePrebid:true,buildId:uploaded.file.id,bidders:[{bidder:'adform',params:{mid:123},enabled:true}]}};}
const save=(f,p)=>savePrebidSettings(f.env,actor,p);
const snap=(f)=>readPreviewSnapshot(f.env.DB,'test-site',{includePrebid:true});
async function generate(f){const settings=await snap(f),resolved=await selectedWorkspaceRuntime(settings,f.env.BUILDS);const {prebidBuilds,...snapshot}=settings;return buildArtifactCandidate({snapshot,pin:resolved.pin,buildTimestamp:'20260913_120000',takeOver:{enabled:true,codelessAdUnitPath:settings.site.gam_path+'Interstitial'},prebid:resolved.prebid});}
test('upload stores unchanged private bytes as archived without changing settings or current file',async()=>{const f=await ready(),before=await snap(f),r=await upload(f);assert(r.created);assert.equal(r.file.status,'archived');assert.equal(r.selectionChanged,false);assert.deepEqual(await snap(f),before);assert.equal((await listPrebidFiles(f.store)).length,1);assert.deepEqual((await readPrebidFile(f.store,r.file.id)).checked.bytes,file());assert(f.log.puts.every(k=>k.startsWith('publishers/test-site/prebid-builds/')));});
test('same bytes retry idempotently without a second record, audit, PUT or active choice',async()=>{const f=await ready(),a=await upload(f),n=f.log.puts.length,b=await upload(f);assert.equal(a.file.id,b.file.id);assert.equal(b.created,false);assert.equal(f.log.puts.length,n);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM audit_log WHERE action='test_workspace.prebid_uploaded'").get().n,1);});
test('changed bytes with same declared version create distinct immutable files',async()=>{const f=await ready(),a=await upload(f),b=await upload(f,file('other'));assert.notEqual(a.file.id,b.file.id);assert.equal((await listPrebidFiles(f.store)).length,2);});
for(const bytes of [new Uint8Array(),new Uint8Array(MAX_PREBID_UPLOAD+1),new TextEncoder().encode('<html>error</html>'),new TextEncoder().encode('not a Prebid file'),new Uint8Array([255,255])])test('invalid uploads do not write storage: '+bytes.length,async()=>{const f=await ready();await assert.rejects(upload(f,bytes));assert.equal(f.log.puts.length,0);assert.equal((await listPrebidFiles(f.store)).length,0);});
test('upload rejects a corrupt existing object and never silently replaces it',async()=>{const f=await ready(),r=await upload(f),key=[...f.objects.keys()][0];f.objects.set(key,file('corrupt'));await assert.rejects(upload(f));assert.deepEqual(f.objects.get(key),file('corrupt'));assert.equal((await listPrebidFiles(f.store)).length,1);});
test('failed registration leaves recoverable bytes, and retry registers the same file',async()=>{const f=await ready();f.faults.batchAt=1;await assert.rejects(upload(f));assert.equal(f.objects.size,1);f.faults.batchAt=-1;assert((await upload(f)).created);assert.equal((await listPrebidFiles(f.store)).length,1);});
test('bounded raw upload validates type, size, stream accounting and cancellation',async()=>{let cancelled=false;const req=new Request('https://test.invalid',{method:'POST',headers:{'content-type':'application/javascript','x-tessera-upload':'prebid-test-file'},body:new ReadableStream({pull(c){c.enqueue(new Uint8Array(MAX_PREBID_UPLOAD+1));},cancel(){cancelled=true;}}),duplex:'half'});await assert.rejects(readPrebidUpload(req),e=>e.status===413);assert(cancelled);await assert.rejects(readPrebidUpload(new Request('https://test.invalid',{method:'POST',body:'x'})),e=>e.status===415);const valid=new Request('https://test.invalid',{method:'POST',headers:{'content-type':'application/javascript','x-tessera-upload':'prebid-test-file'},body:file()});assert.deepEqual(await readPrebidUpload(valid),file());});
test('uploaded file is selected with bidders and exact pin in one atomic commit',async()=>{const f=await ready(),p=await proposal(f),r=await save(f,p);assert(r.persisted&&r.changed);const s=await read(f);assert(s.draft.enablePrebid);assert.equal(s.draft.buildId,p.draft.buildId);assert.equal(s.validationIssue,null);const c=JSON.parse((await snap(f)).config.config_json);assert.equal(c.builtinRuntimeSelection.prebid.id,p.draft.buildId);assert.equal(c.builtinRuntimeSelection.prebid.sha256,p.draft.buildId.slice(8));});
test('Generate embeds same bytes and bidder configuration without changing reference TakeOver',async()=>{const f=await ready();await save(f,await proposal(f));const out=await generate(f);assert.equal(Object.keys(out.files).length,10);assert.deepEqual(out.files['prebid.js'],file());const source=new TextDecoder().decode(out.files['ads.js']);assert.equal(generatedLiteral(source,'HAS_PREBID'),true);assert.deepEqual(generatedLiteral(source,'BIDDERS'),[{bidder:'adform',params:{mid:123}}]);assert.equal(generatedLiteral(source,'TAKEOVER_CODELESS_AD_UNIT_PATH'),'/123/test/Interstitial');assert.equal(out.manifest.runtime.runtimeVersion,'3.10.0-tessera.preview.1');});
test('missing modules block activation without changing current config or deleting file',async()=>{const f=await ready(),p=await proposal(f,file('', ['adformBidAdapter'])),before=await snap(f);await assert.rejects(save(f,p));assert.deepEqual(await snap(f),before);assert.equal((await listPrebidFiles(f.store)).length,1);});
test('uploading a replacement leaves existing selected pin and generated Prebid unchanged',async()=>{const f=await ready();await save(f,await proposal(f));const before=await snap(f);await upload(f,file('new'));assert.deepEqual(await snap(f),before);assert.deepEqual((await generate(f)).files['prebid.js'],file());});
test('explicit replacement archives old build; old bytes remain; OFF retains settings and both files',async()=>{const f=await ready();await save(f,await proposal(f));const a=(await read(f)).draft.buildId;await save(f,await proposal(f,file('new')));const s=await read(f);assert.notEqual(a,s.draft.buildId);assert.equal(s.files.find(x=>x.id===a).status,'archived');await save(f,{expectedRevision:s.revision,acknowledge:true,draft:{...s.draft,enablePrebid:false}});const off=await read(f);assert.equal(off.draft.bidders.length,1);assert.equal(off.files.length,2);assert.equal((await generate(f)).files['prebid.js'],undefined);});
test('runtime-version form preserves active Prebid choice and rejects silent mode changes',async()=>{const f=await ready();await save(f,await proposal(f));const s=await readRuntimeSelectionSettings(f.env);assert(s.selected.prebid);assert.equal(s.enablePrebid,true);await assert.rejects(saveRuntimeSelectionSettings(f.env,actor,{expectedRevision:s.revision,selection:{runtime:s.runtimes[0].pin,allowPreview:true,enablePrebid:false,prebidBuildId:null}}),e=>e.status===422);assert.equal((await saveRuntimeSelectionSettings(f.env,actor,{expectedRevision:s.revision,selection:{runtime:s.runtimes[0].pin,allowPreview:true,enablePrebid:true,prebidBuildId:s.prebidBuildId}})).changed,false);});
test('site editor keeps Prebid selection and refuses removal of override target',async()=>{const f=await ready(),p=await proposal(f);p.draft.overrides=[{bidder:'adform',scopeType:'adunit',scopeKey:'Billboard',params:{mid:456},enabled:true}];await save(f,p);const s=await getSiteDraft(f.env);s.draft.site.gamPath='/123/test1/';await saveSiteDraft(f.env,actor,{expectedRevision:s.revision,acknowledge:true,draft:s.draft});const out=await generate(f);assert.equal(generatedLiteral(new TextDecoder().decode(out.files['ads.js']),'adUnitPath'),'/123/test1/');const u=await getSiteDraft(f.env);u.draft.units=u.draft.units.filter(x=>x.code!=='Billboard');await assert.rejects(saveSiteDraft(f.env,actor,{expectedRevision:u.revision,acknowledge:true,draft:u.draft}));});
test('stale revision and mutation during artifact checks roll back completely',async()=>{const f=await ready(),p=await proposal(f),plan=await preparePrebidSettings(f.env,p);f.sqlite.exec("UPDATE publishers SET name='Newer tab'");const before=await snap(f);await assert.rejects(commitPrebidSettings(f.store,plan,actor),e=>e.status===409);assert.deepEqual(await snap(f),before);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM prebid_builds WHERE status='current'").get().n,0);});
test('chosen archived metadata mutation between check and transaction is rejected',async()=>{const f=await ready(),p=await proposal(f),plan=await preparePrebidSettings(f.env,p);f.sqlite.exec("UPDATE prebid_builds SET modules_json='[]'");await assert.rejects(commitPrebidSettings(f.store,plan,actor),e=>e.status===409);assert.equal(JSON.parse((await snap(f)).config.config_json).enablePrebid,false);});
test('fresh repeated save does not create duplicate audit or mutate other config',async()=>{const f=await ready();const c=JSON.parse((await snap(f)).config.config_json);c.extra={preserve:true};f.sqlite.prepare('UPDATE publisher_configs SET config_json=?').run(JSON.stringify(c));await save(f,await proposal(f));const s=await read(f),r=await save(f,{expectedRevision:s.revision,acknowledge:true,draft:s.draft});assert.equal(r.changed,false);assert.deepEqual(JSON.parse((await snap(f)).config.config_json).extra,{preserve:true});assert.equal(f.sqlite.prepare("SELECT count(*) n FROM audit_log WHERE action='test_workspace.prebid_settings_saved'").get().n,1);});
test('mutation after commit reports uncertainty rather than undoing successfully saved values',async()=>{const f=await ready(),p=await proposal(f),plan=await preparePrebidSettings(f.env,p);const original=f.env.DB.batch;f.env.DB.batch=async(items)=>{const rows=await original(items);throw Error('Lost after COMMIT');};await assert.rejects(commitPrebidSettings(f.store,plan,actor),e=>e.status===503);f.env.DB.batch=original;assert.equal((await read(f)).draft.enablePrebid,true);});
for(const change of [d=>d.bidders[0].params=[],d=>d.bidders.push(d.bidders[0]),d=>d.bidders[0].bidder='unknown',d=>d.bidders[0].params=JSON.parse('{"__proto__":{"x":1}}'),d=>d.bidders[0].params={x:{constructor:1}},d=>d.bidders[0].params={},d=>d.buildId='https://example.invalid/prebid.js'])test('rejects unsupported bidder or build input: '+String(change),async()=>{const f=await ready(),p=await proposal(f),before=await snap(f);change(p.draft);await assert.rejects(save(f,p));assert.deepEqual(await snap(f),before);});
test('new upload may be retried after 50-file quota; a 51st registration is refused',async()=>{const f=await ready(),first=await upload(f);for(let i=1;i<50;i++){const data=await inspectUpload(file(String(i)));f.sqlite.prepare("INSERT INTO prebid_builds(id,publisher_id,version,file_key,modules_json,status) VALUES(?,?,?,?,?,'archived')").run(data.id,'test-site',data.version,data.key,JSON.stringify(data.modules));}assert.equal((await upload(f)).created,false);await assert.rejects(upload(f,file('fifty-one')),e=>e.status===409);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM prebid_builds').get().n,50);});
