import test from 'node:test';
import assert from 'node:assert/strict';
import { unzipSync } from 'fflate';
import worker from '../../worker/test-workspace/index.mjs';
import { issueReceipt, verifyReceipt } from '../../worker/test-workspace/receipt.mjs';
import { schemaSha256 } from '../../worker/test-workspace/schema.mjs';
import { workspaceStore, ORIGIN, TEST_EMAIL, TEST_PASSWORD, TEST_SECRET } from '../support/test-workspace-store.mjs';
import { handleLogin as productionLogin } from '../../worker/auth.ts';
import { sha256 } from '../../worker/runtime/prebid-artifact-check.mjs';
const fixtures=[];
test.afterEach(()=>{while(fixtures.length)fixtures.pop().close();});
const originalFetch=globalThis.fetch;
test.before(()=>{globalThis.fetch=()=>assert.fail('Test workspace must never make an outbound HTTP request');});
test.after(()=>{globalThis.fetch=originalFetch;});
function fixture(){const f=workspaceStore();fixtures.push(f);return f;}
function req(path,{method='GET',body,cookie,origin=ORIGIN,headers={}}={}){return new Request(ORIGIN+path,{method,headers:{...(cookie?{cookie}:{}),...(method==='POST'?{origin,'content-type':'application/json'}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});}
async function login(f,email=TEST_EMAIL){const response=await worker.fetch(new Request(ORIGIN+'/api/auth/login',{method:'POST',headers:{origin:ORIGIN,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({email,password:TEST_PASSWORD})}),f.env);assert.equal(response.status,303,await response.clone().text());return response.headers.get('set-cookie').split(';')[0];}
async function call(f,path,body,cookie){const response=await worker.fetch(req('/test-api/'+path,{method:body===undefined?'GET':'POST',body,cookie}),f.env);let data;try{data=await response.clone().json();}catch{data=null;}return {response,data};}
async function ready(){const f=fixture();const cookie=await login(f);const result=await call(f,'setup',{confirm:'prepare-empty-test-database'},cookie);assert.equal(result.response.status,200,JSON.stringify(result.data));return {f,cookie};}
async function generate(f,cookie,takeOverEnabled=false){const result=await call(f,'generate',{acknowledge:true,takeOverEnabled},cookie);assert.equal(result.response.status,200,JSON.stringify(result.data));return result.data;}
const save=(f,cookie,receipt,note='fixture')=>call(f,'save',{receipt,acknowledge:true,note},cookie);
function forbidDB(f){let accessed=false;Object.defineProperty(f.env,'DB',{get(){accessed=true;throw Error('DB must not be accessed');}});return ()=>assert.equal(accessed,false);}

test('disabled workspace refuses before any database access',async()=>{const f=fixture();f.env.TEST_WORKSPACE_ENABLED='false';const check=forbidDB(f);assert.equal((await worker.fetch(req('/'),f.env)).status,503);check();});
test('production hostname cannot invoke test routes',async()=>{const f=fixture();const check=forbidDB(f);const response=await worker.fetch(new Request('https://prebid-professor.mbaucal.workers.dev/test-api/setup',{method:'POST'}),f.env);assert.equal(response.status,404);check();});
test('wrong resource identity fails closed',async()=>{const f=fixture();f.env.TEST_DATABASE_ID='7ef68f78-0fd8-4937-a774-d2fd1d5353e6';const check=forbidDB(f);assert.equal((await worker.fetch(req('/'),f.env)).status,503);check();});
test('production credential names are not a fallback',async()=>{const f=fixture();delete f.env.TEST_ADMIN_PASSWORD;f.env.ADMIN_PASSWORD=TEST_PASSWORD;const check=forbidDB(f);assert.equal((await worker.fetch(req('/login'),f.env)).status,503);check();});
test('unauthenticated API does not read the database',async()=>{const f=fixture();const check=forbidDB(f);assert.equal((await worker.fetch(req('/test-api/status'),f.env)).status,401);check();});
test('test login issues a secure host-only cookie and no external redirect',async()=>{const f=fixture();const check=forbidDB(f);const cookie=await login(f);assert.match(cookie,/^__Host-pp_session=/);const response=await worker.fetch(req('/',{cookie}),f.env);assert.equal(response.status,200);assert.match(await response.text(),/TEST · NO LIVE PUBLISHING/);check();});
test('same raw key still cannot replay a production session',async()=>{const f=fixture();const response=await productionLogin(new Request(ORIGIN+'/api/auth/login',{method:'POST',headers:{origin:ORIGIN,'content-type':'application/json'},body:JSON.stringify({email:TEST_EMAIL,password:TEST_PASSWORD})}),{ADMIN_EMAIL:TEST_EMAIL,ADMIN_PASSWORD:TEST_PASSWORD,SESSION_SECRET:TEST_SECRET});const cookie=response.headers.get('set-cookie').split(';')[0];const check=forbidDB(f);assert.equal((await worker.fetch(req('/test-api/status',{cookie}),f.env)).status,401);check();});
test('cross-site or missing-Origin mutations are refused',async()=>{const f=fixture();const cookie=await login(f);const check=forbidDB(f);for(const origin of ['https://evil.invalid',''])assert.equal((await worker.fetch(req('/test-api/setup',{method:'POST',cookie,origin,body:{confirm:'prepare-empty-test-database'}}),f.env)).status,403);check();});
test('oversized streamed JSON is refused before initialization',async()=>{const f=fixture();const cookie=await login(f);const check=forbidDB(f);const result=await call(f,'setup',{confirm:'x'.repeat(17000)},cookie);assert.equal(result.response.status,413);check();});
test('status GET leaves an empty database empty',async()=>{const f=fixture();const cookie=await login(f);const {data}=await call(f,'status',undefined,cookie);assert.equal(data.ready,false);assert.equal(f.log.batches,0);assert.equal(f.objects.size,0);});
test('initialization requires the exact confirmation and forbids extra fields',async()=>{const f=fixture();const cookie=await login(f);for(const body of [{confirm:false},{confirm:'prepare-empty-test-database',sql:'DROP TABLE publishers'}])assert.equal((await call(f,'setup',body,cookie)).response.status,422);assert.equal(f.log.batches,0);});
test('one atomic initialization creates only the synthetic site',async()=>{const {f,cookie}=await ready();assert.deepEqual(f.sqlite.prepare('SELECT id,domain,gam_path FROM publishers').all().map((r)=>({...r})),[{id:'test-site',domain:'example.invalid',gam_path:'/123/test/'}]);assert.equal(f.sqlite.prepare('SELECT schema_sha256 FROM tessera_test_environment').get().schema_sha256,schemaSha256);assert.equal(f.log.batches,1);assert.equal(f.objects.size,0);const second=await call(f,'setup',{confirm:'prepare-empty-test-database'},cookie);assert.equal(second.data.created,false);assert.equal(f.log.batches,1);});
test('existing unrecognized database is refused without mutation',async()=>{const f=fixture();f.sqlite.exec("CREATE TABLE publishers(id TEXT); INSERT INTO publishers VALUES ('do-not-touch')");const cookie=await login(f);assert.equal((await call(f,'setup',{confirm:'prepare-empty-test-database'},cookie)).response.status,409);assert.equal(f.log.batches,0);assert.equal(f.sqlite.prepare('SELECT id FROM publishers').get().id,'do-not-touch');});
test('partial schema failure rolls back all application tables',async()=>{const f=fixture();const cookie=await login(f);f.faults.batchAt=5;assert.equal((await call(f,'setup',{confirm:'prepare-empty-test-database'},cookie)).response.status,503);assert.equal(f.sqlite.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE type='table'").get().n,0);f.faults.batchAt=-1;assert.equal((await call(f,'setup',{confirm:'prepare-empty-test-database'},cookie)).response.status,200);});
test('generator uses the actual built-in compiler and does not save',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie,true);assert.equal(reviewed.descriptor.siteId,'test-site');assert.equal(reviewed.descriptor.prebidBuild,null);assert.equal(reviewed.descriptor.completeRelease,false);assert.equal(reviewed.descriptor.files.length,9);assert.match(reviewed.adsJs,/takeOver/);assert.equal(f.objects.size,0);assert.equal(f.sqlite.prepare('SELECT COUNT(*) AS n FROM builtin_draft_uploads').get().n,0);});
test('actual Generate -> Save -> retry -> reopen -> ZIP preserves reviewed bytes',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);const first=await save(f,cookie,reviewed.receipt,'First draft');assert.equal(first.response.status,200,JSON.stringify(first.data));assert.equal(first.data.created,true);const second=await save(f,cookie,reviewed.receipt,'ignored retry note');assert.equal(second.data.created,false);assert.equal(second.data.draft.note,'First draft');assert.equal(f.sqlite.prepare('SELECT COUNT(*) AS n FROM releases').get().n,1);const id=first.data.draft.id;const opened=await call(f,'releases/'+id,undefined,cookie);assert.equal(opened.data.verified,true);assert.equal(opened.data.draft.packageSha256,reviewed.descriptor.packageSha256);const download=await worker.fetch(req('/test-api/releases/'+id+'/download',{cookie}),f.env);assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/^attachment/);const files=unzipSync(new Uint8Array(await download.arrayBuffer()));assert.equal(new TextDecoder().decode(files['ads.js']),reviewed.adsJs);for(const file of reviewed.descriptor.files)assert.equal(await sha256(files[file.name]),file.sha256);});
test('browser-supplied files are rejected before R2 writes',async()=>{const {f,cookie}=await ready();const result=await call(f,'save',{receipt:'x',acknowledge:true,note:'',files:{'ads.js':'bad'}},cookie);assert.equal(result.response.status,422);assert.equal(f.log.puts.length,0);});
test('changed configuration invalidates the reviewed package',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);f.sqlite.prepare("UPDATE publisher_configs SET config_json=? WHERE publisher_id='test-site'").run(JSON.stringify({enablePrebid:false,runtimeControls:{output:{cleanComments:false}}}));const result=await save(f,cookie,reviewed.receipt);assert.equal(result.response.status,409);assert.equal(f.log.puts.length,0);});
test('tampered receipt cannot write a package',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);const [payload,signature]=reviewed.receipt.split('.');const tampered=payload+'.'+(signature[0]==='A'?'B':'A')+signature.slice(1);assert.equal((await save(f,cookie,tampered)).response.status,409);assert.equal(f.log.puts.length,0);});
test('receipt is actor-bound even within the test workspace',async()=>{const {f,cookie}=await ready();f.env.TEST_ADMIN_EMAIL+=',other@example.invalid';const reviewed=await generate(f,cookie);const other=await login(f,'other@example.invalid');assert.equal((await save(f,other,reviewed.receipt)).response.status,409);assert.equal(f.log.puts.length,0);});
test('partial R2 failure keeps tracked bytes and exact retry succeeds',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);f.faults.putName='config.json';const first=await save(f,cookie,reviewed.receipt);assert.equal(first.response.status,503);assert(f.objects.size>0);assert.equal(f.sqlite.prepare('SELECT state FROM builtin_draft_uploads').get().state,'uploading');f.faults.putName='';const retry=await save(f,cookie,reviewed.receipt);assert.equal(retry.response.status,200,JSON.stringify(retry.data));assert.equal(f.sqlite.prepare('SELECT COUNT(*) AS n FROM releases').get().n,1);});
test('lost commit response never deletes a successful stored release',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);f.faults.batchAfter=true;assert.equal((await save(f,cookie,reviewed.receipt)).response.status,503);assert.equal(f.objects.size,9);assert.equal(f.sqlite.prepare('SELECT COUNT(*) AS n FROM releases').get().n,1);f.faults.batchAfter=false;const retry=await save(f,cookie,reviewed.receipt);assert.equal(retry.response.status,200);assert.equal(retry.data.created,false);});
test('corrupt stored files fail rather than being regenerated or repaired',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);const saved=await save(f,cookie,reviewed.receipt);const key=[...f.objects.keys()].find((key)=>key.endsWith('/ads.js'));f.objects.get(key)[0]^=1;const puts=f.log.puts.length;assert.equal((await call(f,'releases/'+saved.data.draft.id,undefined,cookie)).response.status,503);assert.equal((await save(f,cookie,reviewed.receipt)).response.status,503);assert.equal(f.log.puts.length,puts);});
test('quota includes incomplete intents and stops before R2 upload',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);const insert=f.sqlite.prepare("INSERT INTO builtin_draft_uploads (release_id,publisher_id,package_sha256,descriptor_json,created_by,created_at) VALUES (?,'test-site',?,'{}','fixture','2026-01-01')");for(let i=0;i<20;i++)insert.run('quota-'+i,String(i).padStart(64,'0'));const result=await save(f,cookie,reviewed.receipt);assert.equal(result.response.status,409);assert.match(result.data.error,/20-package/);assert.equal(f.log.puts.length,0);});
test('legacy publish, delete, upload and public CDN paths never delegate',async()=>{const {f,cookie}=await ready();const check=forbidDB(f);for(const [path,method] of [['/api/publishers/test-site','DELETE'],['/api/publishers/test-site/publish','POST'],['/cdn/test-site/ads.js','GET'],['/api/monitoring/send','POST'],['/test-api/releases/bad/download','GET'],['/test-api/generate','PUT']]){const response=await worker.fetch(req(path,{method,cookie}),f.env);assert([404,405].includes(response.status));}check();});
test('setup does not persist passwords, session keys or review receipts',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);await save(f,cookie,reviewed.receipt);const audits=JSON.stringify(f.sqlite.prepare('SELECT * FROM audit_log').all());for(const secret of [TEST_PASSWORD,TEST_SECRET,reviewed.receipt])assert(!audits.includes(secret));});
const receiptValues={audience:ORIGIN,actor:TEST_EMAIL,configHash:'a'.repeat(64),runtimeHash:'b'.repeat(64),buildTimestamp:'20260912_120000',takeOverEnabled:false,packageHash:'c'.repeat(64)};
test('receipt expires exactly after 20 minutes',async()=>{const token=await issueReceipt(receiptValues,TEST_SECRET,1000000);assert.equal((await verifyReceipt(token,TEST_SECRET,{actor:TEST_EMAIL,origin:ORIGIN},2199999)).siteId,'test-site');await assert.rejects(verifyReceipt(token,TEST_SECRET,{actor:TEST_EMAIL,origin:ORIGIN},2200000),/expired/);});
test('receipt rejects another origin or signing key',async()=>{const token=await issueReceipt(receiptValues,TEST_SECRET);await assert.rejects(verifyReceipt(token,TEST_SECRET,{actor:TEST_EMAIL,origin:'https://other.invalid'}));await assert.rejects(verifyReceipt(token,TEST_SECRET+'different',{actor:TEST_EMAIL,origin:ORIGIN}));});
test('promotion and site deletion are also guarded in test SQL',async()=>{const {f,cookie}=await ready();const reviewed=await generate(f,cookie);await save(f,cookie,reviewed.receipt);assert.throws(()=>f.sqlite.exec("UPDATE releases SET status='production'"),/TEST_PUBLISH_DISABLED/);assert.throws(()=>f.sqlite.exec('DELETE FROM publishers'),/TEST_SITE_DELETE_DISABLED/);});
