import { useEffect, useMemo, useRef, useState } from 'react';
import builtins from '../../shared/gam/presets.json';
import { expandGroup, type GamRow } from '../../shared/gam/plan.mjs';
import '../api-integrations.css';

type Group={id:string;label:string;pattern:string;count:number;start:number;sizes:string;description:string;names?:string;enabled?:boolean};
type Connection={networkCode:string;name:string;rootId:string;email:string;connectedAt:string};
type Unit={id:string;name:string;code:string;parentId:string;parentPath:{id:string;name:string;code:string}[]};
type CheckedRow=GamRow&{state:string;message?:string;differences?:string[];existing?:{id:string}};
type Review={id:string;rows:CheckedRow[];parent:{name:string;path:string;state:string};network:{name:string;networkCode:string};counts:{new:number;existing:number;conflict:number}};
type Result={id:string;networkCode:string;siteLabel:string;createdAt:string;completed:boolean;error?:string;rows:{name:string;code:string;id:string|null;path:string|null;state:string}[]};
type SiteOption={id:string;name:string;gamPath:string};
const stateName:Record<string,string>={new:'Novo',existing:'Već postoji',conflict:'Konflikt',created:'Kreirano',unconfirmed:'Nije potvrđeno'};

export default function ApiIntegrationsPanel({endpoint='/api/integrations/gam',sites=[]}:{endpoint?:string;sites?:SiteOption[]}){
  const [tab,setTab]=useState<'units'|'connection'|'templates'|'history'>('units');
  const [connections,setConnections]=useState<Connection[]>([]),[configured,setConfigured]=useState(false);
  const [network,setNetwork]=useState(''),[connectNetwork,setConnectNetwork]=useState('');
  const [credential,setCredential]=useState<File|null>(null),fileRef=useRef<HTMLInputElement>(null);
  const [groups,setGroups]=useState<Group[]>(()=>builtins.map(g=>({...g,enabled:true})));
  const [selected,setSelected]=useState(builtins[0].id),[customTemplates,setCustomTemplates]=useState<Group[]>([]);
  const [templateName,setTemplateName]=useState(''),[siteLabel,setSiteLabel]=useState('');
  const [parentMode,setParentMode]=useState<'existing'|'new'>('new');
  const [parentName,setParentName]=useState(''),[parentCode,setParentCode]=useState(''),[parentId,setParentId]=useState('');
  const [parentList,setParentList]=useState<Unit[]>([]),[browsingParent,setBrowsingParent]=useState<Unit|null>(null);
  const [review,setReview]=useState<Review|null>(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<Result|null>(null);
  const [history,setHistory]=useState<Result[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const mounted=useRef(true),epoch=useRef(0);
  const active=connections.find(x=>x.networkCode===network),group=groups.find(x=>x.id===selected)!;
  const allTemplates=[...builtins,...customTemplates];
  const draft=useMemo(()=>{try{const rows=groups.filter(g=>g.enabled).flatMap(expandGroup);const codes=new Set();for(const row of rows){if(codes.has(row.code.toLowerCase()))throw Error(`Dupliran naziv: ${row.code}`);codes.add(row.code.toLowerCase());}if(rows.length>100)throw Error('Najviše 100 ad unita u jednom unosu.');return {rows,error:''};}catch(e){return {rows:[],error:(e as Error).message};}},[groups]);
  async function call<T=Record<string, unknown>>(path:string,body?:unknown):Promise<T>{const r=await fetch(endpoint+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json() as T & {error?:string};if(!r.ok)throw Error(data.error||'Zahtev nije uspeo.');return data;}
  function invalidate(){epoch.current++;setReview(null);setConfirmed(false);setResult(null);setNotice('');}
  function changeGroup(update:Partial<Group>){invalidate();setGroups(current=>current.map(g=>g.id===selected?{...g,...update}:g));}
  async function run(label:string,action:()=>Promise<void>){setBusy(label);setError('');setNotice('');try{await action();}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setBusy('');}}
  async function loadStatus(){const s=await call<{connections:Connection[];configured:boolean}>('/status');if(!mounted.current)return;setConnections(s.connections);setConfigured(s.configured);setNetwork(current=>s.connections.some((x:Connection)=>x.networkCode===current)?current:(s.connections[0]?.networkCode||''));}
  useEffect(()=>{mounted.current=true;void run('Učitavanje',async()=>{await loadStatus();const t=await call<{templates:Group[]}>('/templates');if(mounted.current)setCustomTemplates(t.templates);});return()=>{mounted.current=false;epoch.current++;};},[endpoint]);
  useEffect(()=>{setParentId('');setParentList([]);setBrowsingParent(null);invalidate();},[network]);
  async function browse(id?:string){if(!network)return;const captured=network;await run('Učitavanje parenta',async()=>{const data=await call<{units:Unit[];parent:Unit}>(`/parents?network=${network}${id?'&parent='+id:''}`);if(!mounted.current||captured!==network)return;setParentList(data.units);setBrowsingParent(data.parent);});}
  function chooseParent(unit:Unit){invalidate();setParentId(unit.id);setParentName(unit.name);setParentCode(unit.code);}
  function useTemplate(template:Group){invalidate();setGroups(current=>current.map(g=>g.id===selected?{...template,id:g.id,enabled:true,names:''}:g));}
  function addCustom(){const id=crypto.randomUUID();invalidate();setGroups(current=>[...current,{...builtins[3],id,label:'Sopstveni nazivi',pattern:'Pozicija_{n}',count:1,names:'',enabled:true}]);setSelected(id);}
  async function preview(){await run('Provera u GAM-u',async()=>{const before=epoch.current;const data=await call<Review>('/preview',{networkCode:network,siteLabel,parent:parentMode==='new'?{mode:'new',name:parentName,code:parentCode}:{mode:'existing',id:parentId},rows:draft.rows});if(mounted.current&&epoch.current===before){setReview(data);setConfirmed(false);setResult(null);setNotice('GAM provera je završena. Pregledajte listu pre kreiranja.');}});}
  async function create(){if(!review||!confirmed)return;await run('Kreiranje u GAM-u',async()=>{const data=await call<Result>('/create',{id:review.id,confirmNetwork:review.network.networkCode});if(mounted.current){setResult(data);setReview(null);setConfirmed(false);setNotice(data.completed?'Obrada je završena. GAM ID-jevi i putanje su sačuvani.':'Deo upisa nije potvrđen. Ponovite proveru u GAM-u pre nastavka.');}});}
  async function connect(){await run('Povezivanje',async()=>{if(!credential)throw Error('Izaberite key.json fajl.');if(credential.size>20000)throw Error('JSON ključ je prevelik.');let value;try{value=JSON.parse(await credential.text());}catch{throw Error('Izabrani fajl nije ispravan JSON.');}try{await call('/connect',{networkCode:connectNetwork,credentials:value});await loadStatus();if(mounted.current){setNetwork(connectNetwork);setNotice('GAM mreža je povezana. Otvorite Ad uniti da pripremite pozicije.');}}finally{setCredential(null);if(fileRef.current)fileRef.current.value='';}});}
  async function saveTemplate(){await run('Čuvanje šablona',async()=>{const data=await call<{template:Group}>('/templates',{label:templateName,group:{...group,names:''}});if(mounted.current){setCustomTemplates(current=>[...current,data.template]);setTemplateName('');setNotice('Šablon je sačuvan i dostupan za sledeći unos.');}});}
  const noWrite=!active||!configured||!draft.rows.length||Boolean(draft.error)||(parentMode==='existing'?!parentId:!parentName.trim()||!parentCode.trim());

  return <section className="gam-api" aria-label="API integracije">
    <div className="gam-hero"><div className="gam-provider-icon" aria-hidden="true">G</div><div className="gam-hero-copy"><span className="gam-eyebrow">API INTEGRACIJE</span><h2>Google Ad Manager</h2><p>Povežite mrežu i kreirajte ad unite iz svojih šablona.</p></div><span className={'gam-badge '+(active?'connected':'')}>{active?'Povezano · '+active.networkCode:'Nije povezano'}</span></div>
    <nav className="gam-tabs" aria-label="GAM alati">{([['units','Ad uniti'],['connection','GAM povezivanje'],['templates','Šabloni'],['history','Istorija']] as const).map(([id,label])=><button type="button" key={id} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} disabled={Boolean(busy)} onClick={()=>{setTab(id);setError('');if(id==='history')void run('Učitavanje istorije',async()=>{const data=await call<{results:Result[]}>('/history');if(mounted.current)setHistory(data.results);});}}>{label}</button>)}</nav>
    {error&&<div className="gam-message error" role="alert">{error}</div>}
    {notice&&<div className="gam-message success" role="status">{notice}</div>}
    {busy&&<div className="gam-progress" role="status">{busy}…</div>}
    <fieldset disabled={Boolean(busy)} className="gam-fields">
    {tab==='connection'&&<div className="gam-connection-grid"><article className="gam-card"><span className="gam-step">01 / POVEZIVANJE</span><h3>Dodajte GAM mrežu</h3><p>Koristite isti service account koji već koristite u svojoj skripti.</p>
      {!configured&&<div className="gam-message info">Povezivanje još nije aktivirano na serveru. Šablone i listu ad unita možete pripremiti odmah.<details><summary>Detalji za podešavanje</summary>Na ovom Worker-u dodajte Secret <code>GAM_CREDENTIALS_KEY</code> sa najmanje 32 nasumična znaka. Ključ služi za šifrovanje sačuvanih konekcija.</details></div>}
      <label>Network code<input inputMode="numeric" placeholder="npr. 23339552141" value={connectNetwork} onChange={e=>setConnectNetwork(e.target.value.trim())}/></label>
      <label>Service account JSON<input ref={fileRef} type="file" accept=".json,application/json" disabled={!configured} onChange={e=>setCredential(e.target.files?.[0]||null)}/></label>
      <p className="gam-help">Konekcija se proverava pre čuvanja. Privatni ključ čuva se šifrovano na serveru.</p><button className="gam-primary" type="button" disabled={!configured||!credential||!/^\d+$/.test(connectNetwork)} onClick={()=>void connect()}>Proveri i poveži GAM</button>
      <details><summary>Šta treba da bude podešeno u GAM-u?</summary><p>Uključite API access i dodajte service account email kao korisnika sa pravom pregleda i kreiranja ad unita. Domain-wide delegacija nije deo ove prve verzije.</p></details>
    </article><article className="gam-card"><span className="gam-step">POVEZANE MREŽE</span><h3>Vaše GAM konekcije</h3>{connections.length?connections.map(c=><div className="gam-network" key={c.networkCode}><strong>{c.name}</strong><code>{c.networkCode}</code><small>{c.email}</small><button type="button" onClick={()=>{setNetwork(c.networkCode);setTab('units');}}>Koristi ovu mrežu</button></div>):<p>Još nema sačuvanih konekcija.</p>}</article></div>}
    {tab==='units'&&<>
      {!active&&<div className="gam-message info gam-inline"><span>Pripremite listu sada, a za proveru i kreiranje povežite GAM mrežu.</span><button type="button" onClick={()=>setTab('connection')}>Poveži GAM →</button></div>}
      <article className="gam-card gam-destination"><div><span className="gam-step">01 / ODREDIŠTE</span><h3>Gde kreiramo ad unite?</h3></div><div className="gam-form-grid">
        <label>GAM mreža<select value={network} onChange={e=>setNetwork(e.target.value)}><option value="">Izaberite povezanu mrežu</option>{connections.map(c=><option value={c.networkCode} key={c.networkCode}>{c.name} · {c.networkCode}</option>)}</select></label>
        <label>Sajt / oznaka unosa<input list="gam-site-options" placeholder="npr. politika.rs" value={siteLabel} onChange={e=>{invalidate();setSiteLabel(e.target.value);}}/><datalist id="gam-site-options">{sites.map(s=><option key={s.id} value={s.name}/>)}</datalist></label>
        <label>Parent<select value={parentMode} onChange={e=>{invalidate();setParentMode(e.target.value as 'new'|'existing');setParentId('');setParentName('');setParentCode('');}}><option value="new">Kreiraj novi parent</option><option value="existing">Koristi postojeći parent</option></select></label>
        {parentMode==='new'?<><label>Parent naziv<input placeholder="npr. Politika.rs - Display" value={parentName} onChange={e=>{invalidate();setParentName(e.target.value);}}/></label><label>Parent code<input placeholder="npr. Politika.rs" value={parentCode} onChange={e=>{invalidate();setParentCode(e.target.value);}}/></label></>:<div className="gam-parent-picker"><button type="button" disabled={!active} onClick={()=>void browse()}>Učitaj parente iz GAM-a</button>{parentId&&<p>Izabrano: <strong>{parentName}</strong> <code>{parentId}</code></p>}</div>}
      </div>{parentMode==='existing'&&browsingParent&&<div className="gam-parent-tree"><div><strong>{browsingParent.name}</strong><button type="button" onClick={()=>chooseParent(browsingParent)}>Izaberi ovaj parent</button>{browsingParent.parentId&&<button type="button" onClick={()=>void browse(browsingParent.parentId)}>↑ Jedan nivo gore</button>}</div>{parentList.map(u=><div key={u.id}><span>{u.name} <code>{u.code}</code></span><button type="button" onClick={()=>chooseParent(u)}>Izaberi</button><button type="button" aria-label={`Otvori ${u.name}`} onClick={()=>void browse(u.id)}>Otvori →</button></div>)}</div>}</article>
      <div className="gam-builder"><article className="gam-card"><div className="gam-card-heading"><div><span className="gam-step">02 / POZICIJE</span><h3>Izaberite šablone</h3></div><strong className="gam-total">{draft.rows.length}<small>ad unita</small></strong></div>
        <div className="gam-preset-list">{groups.map(g=><div key={g.id} className={'gam-preset '+(g.id===selected?'selected':'')}><input type="checkbox" aria-label={`Uključi ${g.label}`} checked={Boolean(g.enabled)} onChange={e=>{invalidate();setGroups(current=>current.map(x=>x.id===g.id?{...x,enabled:e.target.checked}:x));}}/><button type="button" onClick={()=>setSelected(g.id)}><span>{g.label}</span><small>{g.names?.trim()?g.names.trim().split('\n').filter(Boolean).length:g.count} pozicija</small></button></div>)}</div><button className="gam-add" type="button" onClick={addCustom}>＋ Dodaj sopstvene nazive</button>
      </article><article className="gam-card gam-editor"><span className="gam-step">PODEŠAVANJA ŠABLONA</span><h3>{group.label}</h3><label>Preuzmi podešavanja iz šablona<select value="" onChange={e=>{const t=allTemplates.find(x=>x.id===e.target.value);if(t)useTemplate(t);}}><option value="">Izaberite šablon…</option>{allTemplates.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>
        <div className="gam-form-grid"><label className="gam-span-2">Naziv / numeracija<input value={group.pattern} onChange={e=>changeGroup({pattern:e.target.value})}/><small>Koristite {'{n}'} za broj: InFeed_{'{n}'} → InFeed_1, InFeed_2…</small></label><label>Broj pozicija<input type="number" min="1" max="100" value={group.count} onChange={e=>changeGroup({count:Number(e.target.value)})}/></label><label>Početni broj<input type="number" min="1" max="1000" value={group.start} onChange={e=>changeGroup({start:Number(e.target.value)})}/></label></div>
        <label>Sopstveni nazivi — jedan po redu<textarea rows={3} placeholder="Ostavite prazno za automatsku numeraciju" value={group.names||''} onChange={e=>changeGroup({names:e.target.value})}/></label>
        <label>Veličine<textarea rows={3} value={group.sizes} onChange={e=>changeGroup({sizes:e.target.value})}/><small>Odvojite tačkom-zarezom. Za Fluid unesite reč Fluid.</small></label><details><summary>Opis u GAM-u</summary><textarea aria-label="Opis u GAM-u" rows={6} value={group.description} onChange={e=>changeGroup({description:e.target.value})}/><p className="gam-help">Opis služi za beleške. Desktop/mobile pravila podešavaju se kroz size mape sajta.</p></details>
        <div className="gam-save-template"><input aria-label="Naziv novog šablona" placeholder="Naziv vašeg šablona" value={templateName} onChange={e=>setTemplateName(e.target.value)}/><button type="button" disabled={!templateName.trim()||Boolean(draft.error)} onClick={()=>void saveTemplate()}>Sačuvaj šablon</button></div>
      </article></div>
      <article className="gam-card"><div className="gam-card-heading"><div><span className="gam-step">03 / PREGLED I KREIRANJE</span><h3>{review?'Provereno u GAM-u':'Pregled pripremljenih ad unita'}</h3></div><button className="gam-primary" type="button" disabled={noWrite} onClick={()=>void preview()}>Proveri u GAM-u</button></div>
        {draft.error&&<div className="gam-message error" role="alert">{draft.error}</div>}
        {review&&<div className="gam-review-summary"><strong>{review.network.name} · {review.network.networkCode}</strong><code>{review.parent.path}</code><span>{review.parent.state==='new'?'Novi parent':'Postojeći parent'} · {review.counts.new} novih · {review.counts.existing} postojećih · {review.counts.conflict} konflikata</span></div>}
        <div className="gam-table-wrap"><table><thead><tr><th>Naziv / code</th><th>Veličine</th><th>Status</th></tr></thead><tbody>{(review?.rows||draft.rows).map((row)=>{const r=row as CheckedRow;return <tr key={r.code}><td><strong>{r.name}</strong><code>{r.code}</code></td><td>{r.sizes}</td><td><span className={'gam-row-state '+(r.state||'')}>{stateName[r.state]||'Pripremljeno'}</span>{r.message&&<small>{r.message}</small>}{Boolean(r.differences?.length)&&<small>Razlike: {r.differences?.join(', ')}. Postojeće vrednosti ostaju.</small>}</td></tr>;})}</tbody></table></div>
        {review&&review.counts.conflict===0&&<div className="gam-create-bar"><label className="gam-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Potvrđujem kreiranje {review.counts.new} ad unita{review.parent.state==='new'?' i novog parenta':''} u GAM mreži {review.network.networkCode}.</label><button className="gam-primary" type="button" disabled={!confirmed} onClick={()=>void create()}>{review.counts.new||review.parent.state==='new'?'Kreiraj u GAM-u':'Sačuvaj rezultat provere'}</button></div>}
        {result&&<div className="gam-result" role="status"><h3>{result.completed?'Rezultat je sačuvan':'Proverite nepotvrđene pozicije'}</h3>{result.error&&<p>{result.error}</p>}<div className="gam-table-wrap"><table><thead><tr><th>Ad unit</th><th>GAM ID / putanja</th><th>Rezultat</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.code}><td>{r.name}</td><td><code>{r.id||'—'}</code><code>{r.path||'—'}</code></td><td>{stateName[r.state]}</td></tr>)}</tbody></table></div></div>}
      </article>
    </>}
    {tab==='templates'&&<article className="gam-card"><span className="gam-step">BIBLIOTEKA</span><h3>Šabloni ad unita</h3><p>Početni šabloni potiču iz tvoje skripte. Svoje varijante sačuvaj iz editora pozicija.</p><div className="gam-template-grid">{allTemplates.map(t=><article key={t.id}><h4>{t.label}</h4><code>{t.pattern}</code><p>{t.sizes}</p><button type="button" onClick={()=>{useTemplate(t);setTab('units');}}>Primeni na izabranu grupu</button></article>)}</div></article>}
    {tab==='history'&&<article className="gam-card"><span className="gam-step">REZULTATI</span><h3>Istorija kreiranja</h3>{!history.length?<p>Sačuvani GAM ID-jevi i putanje pojaviće se ovde nakon prve obrade.</p>:history.map(item=><details key={item.id}><summary>{item.siteLabel||'GAM mreža '+item.networkCode} · {new Date(item.createdAt).toLocaleString('sr-Latn')} · {item.rows.length} pozicija</summary><div className="gam-table-wrap"><table><thead><tr><th>Naziv</th><th>GAM putanja</th><th>Status</th></tr></thead><tbody>{item.rows.map(r=><tr key={r.code}><td>{r.name}</td><td><code>{r.path||'—'}</code></td><td>{stateName[r.state]}</td></tr>)}</tbody></table></div></details>)}</article>}
    </fieldset>
  </section>;
}
