import {useState} from 'react';
import {zipSync,strToU8} from 'fflate';
import {templates,TEMPLATE_VERSION,CREATIVE_RUNTIME_VERSION,getTemplate,exportJson,exportFilename,instructions,normalizeOptions} from '../creative-templates/catalog.mjs';
import '../creative-templates/templates.css';
const labels:Record<string,string>={width:'Širina (px)',height:'Visina (px)',side:'Strana',offset:'Razmak od ivice (px)',minViewport:'Minimalna širina ekrana (px)',contentWidth:'Širina centralnog sadržaja (px)',breakpoint:'Uži slot do (px)'};
function download(name:string,bytes:Uint8Array|string,type:string){const blob=new Blob([typeof bytes==='string'?bytes:bytes.slice().buffer as ArrayBuffer],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export default function CreativeTemplatesPanel(){
 const [selected,setSelected]=useState('incorner'),[settings,setSettings]=useState<Record<string,Record<string,string|number>>>({}),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const t=getTemplate(selected),options={...t.defaults,...settings[selected]};
 function run(all=false){try{setError('');if(all){const files:Record<string,Uint8Array>={};for(const item of templates){const o=settings[item.id]??{};files[exportFilename(item.id)]=strToU8(exportJson(item.id,o));files[`README-${item.id}.txt`]=strToU8(instructions(item.id,o));}download(`tessera-creative-templates-v${TEMPLATE_VERSION}.zip`,zipSync(files),'application/zip');}else download(exportFilename(selected),exportJson(selected,options),'application/json');setNotice(all?'Paket je pripremljen. Raspakujte ZIP i uvezite željene JSON fajlove u GAM.':'JSON je pripremljen za preuzimanje. Sledeći korak je Import u GAM-u.');}catch(e){setError((e as Error).message);}}
 return <section className="ct-panel" aria-label="Creative templates">
  <div className="ct-toolbar"><div><span className="ct-eyebrow">TESSERA CREATIVE LIBRARY · v{TEMPLATE_VERSION}</span><h2>Od šablona do kampanje</h2><p>Izaberite format, podesite izgled i preuzmite šablon za Google Ad Manager.</p></div><button className="ct-secondary" onClick={()=>run(true)}>Preuzmi sve (.zip)</button></div>
  <div className="ct-layout"><nav className="ct-catalog" aria-label="Šabloni">{templates.map(item=><button key={item.id} className={`ct-card ${selected===item.id?'selected':''}`} aria-pressed={selected===item.id} onClick={()=>{setSelected(item.id);setError('');setNotice('');}}><span className={`ct-icon ct-icon-${item.id}`} aria-hidden="true"><i/></span><strong>{item.name}</strong><span>{item.summary}</span><small>{item.size} · {item.kind==='overlay'?'Tessera skripta':'Standardni slot'}</small></button>)}</nav>
  <div className="ct-detail"><div className="ct-detail-title"><div><span className="ct-eyebrow">GAM CUSTOM CREATIVE TEMPLATE</span><h3>{t.name}</h3></div><span className="ct-badge">Test kandidat</span></div>
   <p>{t.summary}</p>
   <div className={`ct-preview ct-preview-${selected}`} aria-label={`Ilustracija formata ${t.name}`}><div className="ct-preview-page"><div/><div/><div/></div><div className="ct-preview-ad" style={{...(t.kind==='overlay'?{[options.side==='left'?'left':'right']:12}:{} )}}><span>OGLAS</span>{t.kind==='overlay'?<b aria-hidden="true">×</b>:null}</div><small>Ilustracija formata</small></div>
   <div className="ct-fields">{t.fields.map((key:string)=><label key={key}>{labels[key]}{key==='side'?<select value={options[key]} onChange={e=>setSettings({...settings,[selected]:{...options,[key]:e.target.value}})}><option value="right">Desno</option><option value="left">Levo</option></select>:<input type="number" min={['width','height'].includes(key)?1:0} max={['width','height'].includes(key)?2000:key==='offset'?100:4000} step="1" value={Number.isNaN(options[key])?'':options[key]} onChange={e=>setSettings({...settings,[selected]:{...options,[key]:e.target.value===''?NaN:Number(e.target.value)}})}/>}</label>)}</div>
   <div className="ct-requirements"><strong>{t.safeFrame?'Radi u standardnom GAM slotu':'Potrebna Tessera skripta '+CREATIVE_RUNTIME_VERSION}</strong><p>{t.safeFrame?'SafeFrame može ostati uključen. Slika i ClickURL se unose pri kreiranju creative-a u GAM-u.':`SafeFrame isključen za ovaj creative. ${selected==='incorner'?'Targetirajte sticky ad unit; skripta prikazuje jedan X i uklanja sticky traku.':'Targetirajte levi ili desni branding ad unit i uskladite size map sa minimalnom širinom ekrana.'}`}</p></div>
   {error?<p className="ct-error" role="alert">{error}</p>:null}{notice?<p className="ct-notice" role="status">{notice}</p>:null}
   <div className="ct-actions"><button className="ct-primary" onClick={()=>run()}>Preuzmi za GAM (.json)</button><button className="ct-secondary" onClick={()=>{try{normalizeOptions(selected,options);download(`README-${selected}.txt`,instructions(selected,options),'text/plain');setError('');}catch(e){setError((e as Error).message);}}}>Preuzmi uputstvo</button></div>
  </div></div>
  <div className="ct-how"><h3>Uvoz u Google Ad Manager</h3><ol><li>Delivery → Creatives → Creative templates</li><li>New creative template → Import → izaberite JSON</li><li>Submit → Save, pa kreirajte creative iz novog šablona</li></ol><p>Šablon priprema polja i kod oglasa. Kampanju, sliku i odredišni URL dodajete u GAM-u. Pre aktivacije proverite uvoz i isporuku u svojoj mreži.</p></div>
 </section>;
}
