"""Named script library: real React + service with all external traffic blocked."""
import base64,json,subprocess,hashlib
from pathlib import Path
from urllib.parse import urlsplit
from playwright.sync_api import sync_playwright
root=Path(__file__).resolve().parent.parent
out=root/'.generated/script-library-ui';out.mkdir(exist_ok=True)
process=subprocess.Popen(['node','scripts/script-library-browser-fixture.mjs'],cwd=root,stdin=subprocess.PIPE,stdout=subprocess.PIPE,text=True)
assert json.loads(process.stdout.readline())['ready']
errors=[];requests=[];checks=[];last_saved=None
def check(name,ok):
 assert ok,name
 checks.append(name)
def route(r):
 global last_saved
 url=urlsplit(r.request.url);assert url.netloc=='tessera.fixture.invalid'
 payload={'path':url.path+('?' + url.query if url.query else ''),'method':r.request.method,'body':r.request.post_data}
 process.stdin.write(json.dumps(payload)+'\n');process.stdin.flush()
 result=json.loads(process.stdout.readline());assert 'error' not in result,result
 body=base64.b64decode(result['body']);requests.append({'method':payload['method'],'status':result['status']})
 if payload['method']=='POST' and result['status'] in [200,201]:last_saved=json.loads(body)['item']
 r.fulfill(status=result['status'],headers=result['headers'],body=body)
try:
 with sync_playwright() as p:
  browser=p.chromium.launch(headless=True);page=browser.new_page(viewport={'width':1280,'height':1000})
  page.route('**/*',route);page.on('pageerror',lambda e:errors.append(str(e)))
  page.goto('https://tessera.fixture.invalid/');page.get_by_role('button',name='Save script version',exact=True).wait_for()
  check('Opening the library is read-only',all(r['method']=='GET' for r in requests))
  page.get_by_label('Script name',exact=True).fill('Standard 10s')
  page.get_by_label('Refresh',exact=True).select_option('fixed');page.get_by_label('Standard interval (seconds)',exact=True).fill('10')
  page.get_by_role('button',name='Save script version',exact=True).click();page.get_by_role('status').filter(has_text='Script saved').wait_for()
  first=last_saved.copy()
  cache_name='Cache-60s-'+('LongName'*8)
  check('Releases has a cache summary, not a second cache form',page.get_by_label('Auction mode',exact=True).count()==0 and page.get_by_text('Bid caching: Off',exact=True).is_visible())
  page.get_by_role('button',name='Edit Prebid settings',exact=True).click()
  cache=page.get_by_role('checkbox',name='Reuse valid, unused bids',exact=True);cache.wait_for();cache.check()
  page.get_by_label('Maximum bid age (seconds)',exact=True).fill('60')
  page.get_by_role('button',name='Save Prebid settings',exact=True).click()
  page.get_by_text('Prebid settings saved.',exact=False).wait_for()
  check('Saving Demand does not generate a script',sum(r['method']=='POST' for r in requests)==1)
  page.set_viewport_size({'width':390,'height':844})
  check('Demand cache settings fit mobile',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
  page.screenshot(path=str(out/'demand-mobile.png'),full_page=True)
  page.set_viewport_size({'width':1280,'height':1000})
  page.get_by_role('button',name='Releases',exact=True).click()
  page.get_by_text('Bid caching: On',exact=True).wait_for()
  page.get_by_label('Script name',exact=True).fill(cache_name)
  page.get_by_label('Refresh',exact=True).select_option('fixed');page.get_by_label('Standard interval (seconds)',exact=True).fill('10')
  page.get_by_role('button',name='Save script version',exact=True).click();page.get_by_role('status').filter(has_text='Script saved').wait_for()
  second=last_saved.copy()
  check('Named standalone cache version saved',second['name']==cache_name and second['settings']['mode']=='auction-with-cache' and second['settings']['refreshSeconds']==10)
  card=page.get_by_role('article',name='Script: '+cache_name,exact=True)
  with page.expect_download() as downloaded:card.get_by_role('button',name='Download standalone ZIP',exact=True).click()
  downloaded.value.save_as(str(out/'standalone.zip'))
  check('Standalone download has the chosen name and verified bytes',downloaded.value.suggested_filename.startswith(cache_name) and hashlib.sha256((out/'standalone.zip').read_bytes()).hexdigest()==second['sha256'])
  page.get_by_label('Test name',exact=True).fill('Standard vs Cache')
  page.get_by_label('Script A',exact=True).select_option(first['id']);page.get_by_label('Script B',exact=True).select_option(second['id'])
  page.get_by_label('Traffic to B (%)',exact=True).fill('10')
  page.get_by_role('button',name='Save A/B test',exact=True).click();page.get_by_role('status').filter(has_text='A/B test saved').wait_for()
  saved_test=last_saved.copy()
  check('A/B test references exact named saved versions',saved_test['scripts']['A']['id']==first['id'] and saved_test['scripts']['B']['id']==second['id'] and saved_test['trafficBPercent']==10)
  with page.expect_download() as downloaded:page.get_by_role('article',name='Test: Standard vs Cache',exact=True).get_by_role('button',name='Download A/B ZIP',exact=True).click()
  downloaded.value.save_as(str(out/'test.zip'));check('Test ZIP matches saved version',hashlib.sha256((out/'test.zip').read_bytes()).hexdigest()==saved_test['sha256'])
  page.screenshot(path=str(out/'desktop.png'),full_page=True)
  page.reload();page.get_by_role('article',name='Script: '+cache_name,exact=True).wait_for();page.get_by_role('article',name='Test: Standard vs Cache',exact=True).wait_for()
  check('Saved names and references survive reload',page.get_by_role('article',name='Script: Standard 10s',exact=True).count()==1)
  page.get_by_role('article',name='Script: '+cache_name,exact=True).get_by_role('button',name='Create new version').click()
  page.get_by_role('button',name='Edit Prebid settings',exact=True).click()
  page.get_by_label('Maximum bid age (seconds)',exact=True).fill('30')
  page.get_by_role('button',name='Save Prebid settings',exact=True).click();page.get_by_text('Prebid settings saved.',exact=False).wait_for()
  page.get_by_role('button',name='Releases',exact=True).click();page.get_by_text('Bid caching: On',exact=True).wait_for()
  page.get_by_label('Script name',exact=True).fill('Cache 30s')
  page.get_by_role('button',name='Save script version',exact=True).click();page.get_by_role('status').filter(has_text='Script saved').wait_for()
  check('Editing Demand creates a separate version without changing the saved test',last_saved['settings']['maxBidAgeSeconds']==30 and last_saved['id']!=second['id'] and cache_name in page.get_by_role('article',name='Test: Standard vs Cache',exact=True).inner_text())
  page.get_by_role('button',name='Save script version',exact=True).click();page.get_by_role('status').filter(has_text='already saved').wait_for()
  check('Same name and settings do not duplicate the version',page.get_by_role('article',name='Script: Cache 30s',exact=True).count()==1)
  page.get_by_label('Test name',exact=True).fill('Cache A/A');page.get_by_label('Script A',exact=True).select_option(second['id']);page.get_by_label('Script B',exact=True).select_option(second['id'])
  check('Same version can be chosen for A/A',page.get_by_text('Both variants use the same script.',exact=False).is_visible())
  page.get_by_role('button',name='Save A/B test',exact=True).click();page.get_by_role('status').filter(has_text='A/B test saved').wait_for()
  page.set_viewport_size({'width':390,'height':844});page.get_by_role('article',name='Script: '+cache_name,exact=True).get_by_text('Version details',exact=True).click()
  check('Long names and version identities fit mobile',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
  page.screenshot(path=str(out/'mobile.png'),full_page=True);check('No unhandled UI error',not errors)
  card=page.get_by_role('article',name='Script: '+cache_name,exact=True)
  before=len(requests);card.get_by_role('button',name='Delete',exact=True).click()
  dialog=page.get_by_role('dialog',name='Are you sure?',exact=True);dialog.wait_for()
  check('Confirmation names the exact script and defaults to No',cache_name in dialog.inner_text() and page.evaluate('document.activeElement.textContent')=='No')
  dialog.get_by_role('button',name='No',exact=True).click()
  check('No causes no request or deletion',len(requests)==before and card.count()==1)
  card.get_by_role('button',name='Delete',exact=True).click();dialog.wait_for();page.keyboard.press('Escape')
  check('Escape causes no request or deletion',len(requests)==before and card.count()==1)
  card.get_by_role('button',name='Delete',exact=True).click();dialog.wait_for()
  page.screenshot(path=str(out/'delete-confirmation-mobile.png'))
  dialog.get_by_role('button',name='Yes',exact=True).click();card.wait_for(state='detached')
  check('Yes deletes only the selected script',sum(r['method']=='DELETE' for r in requests)==1 and page.get_by_role('article',name='Script: Standard 10s',exact=True).count()==1)
  check('Existing saved test keeps its script names',cache_name in page.get_by_role('article',name='Test: Standard vs Cache',exact=True).inner_text())
  page.get_by_text('Deleted scripts and tests',exact=True).click()
  page.get_by_role('article',name='Deleted: '+cache_name,exact=True).get_by_role('button',name='Restore',exact=True).click();card.wait_for()
  with page.expect_download() as downloaded:card.get_by_role('button',name='Download standalone ZIP',exact=True).click()
  downloaded.value.save_as(str(out/'restored.zip'))
  check('Restore recovers the exact original ZIP',hashlib.sha256((out/'restored.zip').read_bytes()).hexdigest()==second['sha256'])
  test_card=page.get_by_role('article',name='Test: Cache A/A',exact=True)
  test_card.get_by_role('button',name='Delete',exact=True).click();dialog.wait_for();dialog.get_by_role('button',name='Yes',exact=True).click();test_card.wait_for(state='detached')
  check('Deleting a test preserves its source script',card.count()==1)
  check('Deletion UI has no unhandled error',not errors)
  page.get_by_role('button',name='Demand → Prebid',exact=True).click()
  page.get_by_role('checkbox',name='Reuse valid, unused bids',exact=True).wait_for()
  check('Demand settings persist after leaving Releases',page.get_by_label('Maximum bid age (seconds)',exact=True).input_value()=='30')
  page.get_by_role('radio').nth(1).check()
  check('AdX-only hides cache controls',page.get_by_role('checkbox',name='Reuse valid, unused bids',exact=True).count()==0)
  page.get_by_role('button',name='Save Prebid settings',exact=True).click();page.get_by_text('AdX-only mode is enabled.',exact=False).wait_for()
  page.get_by_role('button',name='Releases',exact=True).click();page.get_by_role('button',name='Save script version',exact=True).wait_for()
  check('Demand off disables new scripts but preserves saved versions',page.get_by_role('button',name='Save script version',exact=True).is_disabled() and page.get_by_role('article',name='Script: Standard 10s',exact=True).count()==1)
  page.get_by_role('button',name='Edit Prebid settings',exact=True).first.click();page.get_by_role('radio').first.check()
  check('Re-enabling Prebid restores its cache choices',page.get_by_role('checkbox',name='Reuse valid, unused bids',exact=True).is_checked() and page.get_by_label('Maximum bid age (seconds)',exact=True).input_value()=='30')
  page.get_by_role('checkbox',name='Reuse valid, unused bids',exact=True).uncheck()
  page.get_by_role('button',name='Save Prebid settings',exact=True).click();page.get_by_text('Prebid settings saved.',exact=False).wait_for()
  page.get_by_role('button',name='Ad positions',exact=True).click()
  def position(code):return page.locator('.ad-unit-card').filter(has=page.locator('code',has_text=code))
  position('Sticky').get_by_role('button',name='Bid cache: Off',exact=True).click()
  cache_dialog=page.get_by_role('dialog',name='Bid cache · Sticky',exact=True)
  cache_dialog.get_by_label('Bid cache for Sticky',exact=True).select_option('on')
  cache_dialog.get_by_role('button',name='Save position setting').click();cache_dialog.get_by_role('status').wait_for()
  check('Position on overrides site off',cache_dialog.get_by_text('Effective: On',exact=True).is_visible())
  check('Position modal fits mobile',cache_dialog.bounding_box()['width']<=390)
  page.screenshot(path=str(out/'position-cache-mobile.png'))
  page.keyboard.press('Escape');cache_dialog.wait_for(state='detached')
  position('Billboard').get_by_role('button',name='Bid cache: Off',exact=True).click()
  page.get_by_label('Bid cache for Billboard',exact=True).select_option('off')
  page.get_by_role('button',name='Save position setting').click();page.get_by_role('status').wait_for()
  page.get_by_role('button',name='Close bid cache settings').click()
  check('Saving another position preserves existing override',position('Sticky').get_by_role('button',name='Bid cache: On',exact=True).is_visible())
  page.get_by_role('button',name='Demand → Prebid',exact=True).click()
  page.get_by_role('checkbox',name='Reuse valid, unused bids',exact=True).check()
  page.get_by_role('button',name='Save Prebid settings',exact=True).click();page.get_by_text('Prebid settings saved.',exact=False).wait_for()
  page.get_by_role('button',name='Ad positions',exact=True).click()
  position('Billboard').get_by_role('button',name='Bid cache: Off',exact=True).wait_for()
  check('Changing site default preserves explicit position off',position('Sticky').get_by_role('button',name='Bid cache: On',exact=True).is_visible())
  page.get_by_role('button',name='Releases',exact=True).click()
  page.get_by_label('Script name',exact=True).fill('Position cache')
  page.get_by_role('button',name='Save script version',exact=True).click();page.get_by_role('status').filter(has_text='Script saved').wait_for()
  check('Saved package captures position choices',last_saved['settings']['positionOverrides']=={'Billboard':False,'Sticky':True} and last_saved['id'].startswith('tanjug-script-2.0.0-'))
  page.get_by_role('button',name='Ad positions',exact=True).click()
  position('Billboard').get_by_role('button',name='Bid cache: Off',exact=True).click()
  page.get_by_label('Bid cache for Billboard',exact=True).select_option('inherit')
  page.get_by_role('button',name='Save position setting').click();page.get_by_role('status').wait_for()
  check('Returning to site setting uses current default',page.get_by_text('Effective: On',exact=True).is_visible())
  page.get_by_role('button',name='Close bid cache settings').click()
  page.reload();page.get_by_role('button',name='Ad positions',exact=True).click()
  position('Billboard').get_by_role('button',name='Bid cache: On',exact=True).wait_for()
  check('Inherited setting survives reload',position('Sticky').get_by_role('button',name='Bid cache: On',exact=True).is_visible())
  check('Position settings introduce no UI error',not errors)
  browser.close()
finally:
 process.stdin.close();process.wait(timeout=10)
(out/'report.json').write_text(json.dumps({'checks':checks,'passed':len(checks),'failed':0,'errors':errors,'requests':requests},indent=2))
print(json.dumps({'passed':len(checks),'failed':0}))
